const listeButeurs = [
    { nom: "C. Ronaldo",        pays: "Portugal",        image: "../images/CR7.png",                   buts: 0 },
    { nom: "Neymar",            pays: "Brésil",           image: "../images/Neymar.png",                buts: 0 },
    { nom: "E. Haaland",        pays: "Norvège",          image: "../images/Haaland.png",               buts: 0 },
    { nom: "L. Messi",          pays: "Argentine",        image: "../images/Messi.png",                 buts: 0 },
    { nom: "K. Mbappé",         pays: "France",           image: "../images/Mbap.png",                  buts: 0 },
    { nom: "A. Taggart",        pays: "Australie",        image: "../images/Adam_Taggart.webp",         buts: 0 },
    { nom: "A. Afif",           pays: "Qatar",            image: "../images/Akram_Afif.png",            buts: 0 },
    { nom: "A. Kramarić",       pays: "Croatie",          image: "../images/Andrej_Kramarić.jpeg",      buts: 0 },
    { nom: "A. Semenyo",        pays: "Ghana",            image: "../images/Antoine_Semenyo.png",       buts: 0 },
    { nom: "B. Embolo",         pays: "Suisse",           image: "../images/Breel_Embolo.png",          buts: 0 },
    { nom: "C. Bakambu",        pays: "RD Congo",         image: "../images/Cédric_Bakambu.jpeg",       buts: 0 },
    { nom: "C. Wood",           pays: "Nouvelle-Zélande", image: "../images/Chris_Wood.png",            buts: 0 },
    { nom: "C. Pulisic",        pays: "États-Unis",       image: "../images/Christian_Pulisic.png",     buts: 0 },
    { nom: "D. Núñez",          pays: "Uruguay",          image: "../images/Darwin_Núñez.jpeg",         buts: 0 },
    { nom: "E. Shomurodov",     pays: "Ouzbékistan",      image: "../images/Eldor_Shomurodov.png",      buts: 0 },
    { nom: "E. Valencia",       pays: "Équateur",         image: "../images/Enner_Valencia.png",       buts: 0 },
    { nom: "E. Demirović",      pays: "Bosnie",           image: "../images/Ermedin_Demirović.webp",    buts: 0 },
    { nom: "F. Wirtz",          pays: "Allemagne",        image: "../images/Florian_Wirtz.png",         buts: 0 },
    { nom: "F. Pierrot",        pays: "Haïti",            image: "../images/Frantzdy_Pierrot.jpg",      buts: 0 },
    { nom: "H. Kane",           pays: "Angleterre",       image: "../images/Harry_Kane.png",            buts: 0 },
    { nom: "H. Martín",         pays: "Mexique",          image: "../images/Henry_Martín.png",          buts: 0 },
    { nom: "I. Díaz",           pays: "Panama",           image: "../images/Ismael_Díaz.webp",          buts: 0 },
    { nom: "K. Mitoma",         pays: "Japon",            image: "../images/Kaoru_Mitoma.png",          buts: 0 },
    { nom: "K. Yıldız",         pays: "Turquie",          image: "../images/Kenan_Yıldız.jpeg",         buts: 0 },
    { nom: "L. Yamal",          pays: "Espagne",          image: "../images/Lamine_Yamal.png",          buts: 0 },
    { nom: "L. Martínez",       pays: "Argentine",        image: "../images/Lautaro_Martínez.png",      buts: 0 },
    { nom: "L. Shankland",      pays: "Écosse",           image: "../images/Lawrence_Shankland.png",    buts: 0 },
    { nom: "L. Bacuna",         pays: "Curaçao",          image: "../images/Leandro_Bacuna.jpg",        buts: 0 },
    { nom: "L. Díaz",           pays: "Colombie",         image: "../images/Luis_Díaz.avif",            buts: 0 },
    { nom: "M. Arnautović",     pays: "Autriche",         image: "../images/Marko_Arnautović.png",      buts: 0 },
    { nom: "M. Taremi",         pays: "Iran",             image: "../images/Mehdi_Taremi.png",          buts: 0 },
    { nom: "M. Almirón",        pays: "Paraguay",         image: "../images/Miguel_Almirón.png",        buts: 0 },
    { nom: "M. Salah",          pays: "Égypte",           image: "../images/Mohamed_Salah.png",         buts: 0 },
    { nom: "Mohanad Ali",       pays: "Irak",             image: "../images/Mohanad_Ali.jpg",           buts: 0 },
    { nom: "M. Al-Tamari",      pays: "Jordanie",         image: "../images/Mousa_Al-Tamari.png",       buts: 0 },
    { nom: "L. Paquetá",        pays: "Brésil",           image: "../images/Paquetarmv.png",               buts: 0 },
    { nom: "P. Schick",         pays: "Rép. tchèque",     image: "../images/Patrik_Schick.png",         buts: 0 },
    { nom: "P. Tau",            pays: "Afrique du Sud",   image: "../images/Percy_Tau.jpeg",            buts: 0 },
    { nom: "R. Jiménez",        pays: "Mexique",          image: "../images/Raúl_Jiménez.png",          buts: 0 },
    { nom: "R. Mahrez",         pays: "Algérie",          image: "../images/Riyad_Mahrez.png",          buts: 0 },
    { nom: "R. Lukaku",         pays: "Belgique",         image: "../images/Romelu_Lukaku.png",         buts: 0 },
    { nom: "R. Mendes",         pays: "Cap-Vert",         image: "../images/Ryan_Mendes.webp",          buts: 0 },
    { nom: "S. Mané",           pays: "Sénégal",          image: "../images/Sadio_Mané.png",            buts: 0 },
    { nom: "S. Al-Dawsari",     pays: "Arabie Saoudite",  image: "../images/Salem_Al-Dawsari.png",      buts: 0 },
    { nom: "S. Haller",         pays: "Côte d'Ivoire",    image: "../images/Sébastien_Haller.png",      buts: 0 },
    { nom: "Son Heung-min",     pays: "Corée du Sud",     image: "../images/Son_Heung-min.png",         buts: 0 },
    { nom: "V. Gyökeres",       pays: "Suède",            image: "../images/Viktor_Gyökeres.png",       buts: 0 },
    { nom: "Vinicius Jr",       pays: "Brésil",           image: "../images/Vinicius_Jr.png",           buts: 0 },
    { nom: "Y. En-Nesyri",      pays: "Maroc",            image: "../images/Youssef_En-Nesyri.png",     buts: 0 },
    { nom: "Y. Msakni",         pays: "Tunisie",          image: "../images/Youssef_Msakni.webp",       buts: 0 },
    { nom: "J. David",          pays: "Canada",           image: "../images/Jonathan_David.png",        buts: 0 },
    { nom: "C. Gakpo",          pays: "Pays-Bas",         image: "../images/Cody_Gakpo.png",            buts: 0 },
]