const listeButeurs = [
    { nom: "Cristiano Ronaldo",  nomAPI: "Cristiano Ronaldo",       pays: "Portugal",        image: "../images/buteur/CR7.png",                   buts: 0 },
    { nom: "Neymar",             nomAPI: "Neymar",            pays: "Brésil",           image: "../images/buteur/Neymar.png",                buts: 0 },
    { nom: "Erling Haaland",     nomAPI: "Erling Haaland",        pays: "Norvège",          image: "../images/buteur/Haaland.png",               buts: 0 },
    { nom: "Lionel Messi",       nomAPI: "Lionel Messi",          pays: "Argentine",        image: "../images/buteur/Messi.png",                 buts: 0 },
    { nom: "Kylian Mbappé",      nomAPI: "Kylian Mbappé",         pays: "France",           image: "../images/buteur/Mbap.png",                  buts: 0 },
    { nom: "Adam Taggart",       nomAPI: "A. Taggart",        pays: "Australie",        image: "../images/buteur/Adam_Taggart.webp",         buts: 0 },
    { nom: "Akram Afif",         nomAPI: "A. Afif",           pays: "Qatar",            image: "../images/buteur/Akram_Afif.png",            buts: 0 },
    { nom: "Andrej Kramarić",    nomAPI: "A. Kramarić",       pays: "Croatie",          image: "../images/buteur/Andrej_Kramarić.jpeg",      buts: 0 },
    { nom: "Antoine Semenyo",    nomAPI: "A. Semenyo",        pays: "Ghana",            image: "../images/buteur/Antoine_Semenyo.png",       buts: 0 },
    { nom: "Breel Embolo",       nomAPI: "Breel Embolo",      pays: "Suisse",           image: "../images/buteur/Breel_Embolo.png",          buts: 0 },
    { nom: "Folarin Balogun",    nomAPI: "F. Balogun",        pays: "États-Unis",       image: "../images/buteur/F. Balogun.png",            buts: 0 },
    { nom: "Giovanni Reyna",     nomAPI: "G. Reyna",          pays: "États-Unis",       image: "../images/buteur/G. Reyna.webp",             buts: 0 },
    { nom: "Cyle Larin",         nomAPI: "C. Larin",          pays: "Canada",           image: "../images/buteur/C. Larin.png",              buts: 0 },
    { nom: "Maurício",           nomAPI: "Maurício",          pays: "Paraguay",         image: "../images/buteur/Maurício.png",              buts: 0 },
    { nom: "Jovo Lukić",         nomAPI: "Jovo Lukić",        pays: "Bosnie-Herzég.",   image: "../images/buteur/Jovo Lukić.avif",           buts: 0 },
    { nom: "Cédric Bakambu",     nomAPI: "C. Bakambu",        pays: "RD Congo",         image: "../images/buteur/Cédric_Bakambu.jpeg",       buts: 0 },
    { nom: "Chris Wood",         nomAPI: "C. Wood",           pays: "Nouvelle-Zélande", image: "../images/buteur/Chris_Wood.png",            buts: 0 },
    { nom: "Christian Pulisic",  nomAPI: "C. Pulisic",        pays: "États-Unis",       image: "../images/buteur/Christian_Pulisic.png",     buts: 0 },
    { nom: "Darwin Núñez",       nomAPI: "D. Núñez",          pays: "Uruguay",          image: "../images/buteur/Darwin_Núñez.jpeg",         buts: 0 },
    { nom: "Eldor Shomurodov",   nomAPI: "E. Shomurodov",     pays: "Ouzbékistan",      image: "../images/buteur/Eldor_Shomurodov.png",      buts: 0 },
    { nom: "Enner Valencia",     nomAPI: "E. Valencia",       pays: "Équateur",         image: "../images/buteur/Enner_Valencia.png",        buts: 0 },
    { nom: "Ermedin Demirović",  nomAPI: "E. Demirović",      pays: "Bosnie",           image: "../images/buteur/Ermedin_Demirović.webp",    buts: 0 },
    { nom: "Florian Wirtz",      nomAPI: "F. Wirtz",          pays: "Allemagne",        image: "../images/buteur/Florian_Wirtz.png",         buts: 0 },
    { nom: "Frantzdy Pierrot",   nomAPI: "F. Pierrot",        pays: "Haïti",            image: "../images/buteur/Frantzdy_Pierrot.jpg",      buts: 0 },
    { nom: "Harry Kane",         nomAPI: "H. Kane",           pays: "Angleterre",       image: "../images/buteur/Harry_Kane.png",            buts: 0 },
    { nom: "Hwang In-beom",      nomAPI: "I.B. Hwang",     pays: "Corée du Sud",     image: "../images/buteur/Hwang_In-beom.webp",        buts: 0 },
    { nom: "Henry Martín",       nomAPI: "H. Martín",         pays: "Mexique",          image: "../images/buteur/Henry_Martín.png",          buts: 0 },
    { nom: "Ismael Díaz",        nomAPI: "I. Díaz",           pays: "Panama",           image: "../images/buteur/Ismael_Díaz.webp",          buts: 0 },
    { nom: "Kaoru Mitoma",       nomAPI: "K. Mitoma",         pays: "Japon",            image: "../images/buteur/Kaoru_Mitoma.png",          buts: 0 },
    { nom: "Kenan Yıldız",       nomAPI: "K. Yıldız",         pays: "Turquie",          image: "../images/buteur/Kenan_Yıldız.jpeg",         buts: 0 },
    { nom: "Ladislav Krejčí",    nomAPI: "L. Krejčí",         pays: "Rép. tchèque",     image: "../images/buteur/L.Krejčí.png",              buts: 0 },
    { nom: "Lamine Yamal",       nomAPI: "Lamine Yamal",          pays: "Espagne",          image: "../images/buteur/Lamine_Yamal.png",          buts: 0 },
    { nom: "Lautaro Martínez",   nomAPI: "Lautaro Martínez",       pays: "Argentine",        image: "../images/buteur/Lautaro_Martínez.png",      buts: 0 },
    { nom: "Lawrence Shankland", nomAPI: "L. Shankland",      pays: "Écosse",           image: "../images/buteur/Lawrence_Shankland.png",    buts: 0 },
    { nom: "Leandro Bacuna",     nomAPI: "L. Bacuna",         pays: "Curaçao",          image: "../images/buteur/Leandro_Bacuna.jpg",        buts: 0 },
    { nom: "Luis Díaz",          nomAPI: "L. Díaz",           pays: "Colombie",         image: "../images/buteur/Luis_Díaz.avif",            buts: 0 },
    { nom: "Marko Arnautović",   nomAPI: "Marko Arnautović",     pays: "Autriche",         image: "../images/buteur/Marko_Arnautović.png",      buts: 0 },
    { nom: "Mehdi Taremi",       nomAPI: "M. Taremi",         pays: "Iran",             image: "../images/buteur/Mehdi_Taremi.png",          buts: 0 },
    { nom: "Miguel Almirón",     nomAPI: "M. Almirón",        pays: "Paraguay",         image: "../images/buteur/Miguel_Almirón.png",        buts: 0 },
    { nom: "Mohamed Salah",      nomAPI: "Mohamed Salah",          pays: "Égypte",           image: "../images/buteur/Mohamed_Salah.png",         buts: 0 },
    { nom: "Mohanad Ali",        nomAPI: "Mohanad Ali",       pays: "Irak",             image: "../images/buteur/Mohanad_Ali.jpg",           buts: 0 },
    { nom: "Mousa Al-Tamari",    nomAPI: "M. Al-Tamari",      pays: "Jordanie",         image: "../images/buteur/Mousa_Al-Tamari.png",       buts: 0 },
    { nom: "Lucas Paquetá",      nomAPI: "L. Paquetá",        pays: "Brésil",           image: "../images/buteur/Paquetarmv.png",            buts: 0 },
    { nom: "Patrik Schick",      nomAPI: "P. Schick",         pays: "Rép. tchèque",     image: "../images/buteur/Patrik_Schick.png",         buts: 0 },
    { nom: "Percy Tau",          nomAPI: "P. Tau",            pays: "Afrique du Sud",   image: "../images/buteur/Percy_Tau.jpeg",            buts: 0 },
    { nom: "Julián Quiñones",    nomAPI: "J. Quiñones",       pays: "Mexique",          image: "../images/buteur/J. Quiñones.png",           buts: 0 },
    { nom: "Raúl Jiménez",       nomAPI: "R. Jiménez",        pays: "Mexique",          image: "../images/buteur/Raúl_Jiménez.png",          buts: 0 },
    { nom: "Riyad Mahrez",       nomAPI: "Riyad Mahrez",         pays: "Algérie",          image: "../images/buteur/Riyad_Mahrez.png",          buts: 0 },
    { nom: "Romelu Lukaku",      nomAPI: "Romelu Lukaku",         pays: "Belgique",         image: "../images/buteur/Romelu_Lukaku.png",         buts: 0 },
    { nom: "Ryan Mendes",        nomAPI: "R. Mendes",         pays: "Cap-Vert",         image: "../images/buteur/Ryan_Mendes.webp",          buts: 0 },
    { nom: "Sadio Mané",         nomAPI: "S. Mané",           pays: "Sénégal",          image: "../images/buteur/Sadio_Mané.png",            buts: 0 },
    { nom: "Salem Al-Dawsari",   nomAPI: "S. Al-Dawsari",     pays: "Arabie Saoudite",  image: "../images/buteur/Salem_Al-Dawsari.png",      buts: 0 },
    { nom: "Sébastien Haller",   nomAPI: "S. Haller",         pays: "Côte d'Ivoire",    image: "../images/buteur/Sébastien_Haller.png",      buts: 0 },
    { nom: "Oh Hyeon-gyu",       nomAPI: "H.G. Oh",      pays: "Corée du Sud",     image: "../images/buteur/oh hyeon-gyu.webp",         buts: 0 },
    { nom: "Son Heung-min",      nomAPI: "H.M Son",     pays: "Corée du Sud",     image: "../images/buteur/Son_Heung-min.png",         buts: 0 },
    { nom: "Viktor Gyökeres",    nomAPI: "V. Gyökeres",       pays: "Suède",            image: "../images/buteur/Viktor_Gyökeres.png",       buts: 0 },
    { nom: "Vinícius Júnior",        nomAPI: "Vinícius Júnior",       pays: "Brésil",           image: "../images/buteur/Vinicius_Jr.png",           buts: 0 },
    { nom: "Youssef En-Nesyri",  nomAPI: "Y. En-Nesyri",      pays: "Maroc",            image: "../images/buteur/Youssef_En-Nesyri.png",     buts: 0 },
    { nom: "Youssef Msakni",     nomAPI: "Y. Msakni",         pays: "Tunisie",          image: "../images/buteur/Youssef_Msakni.webp",       buts: 0 },
    { nom: "Jonathan David",     nomAPI: "Jonathan David",          pays: "Canada",           image: "../images/buteur/Jonathan_David.png",        buts: 0 },
    { nom: "Cody Gakpo",         nomAPI: "C. Gakpo",          pays: "Pays-Bas",         image: "../images/buteur/Cody_Gakpo.png",            buts: 0 },
    { nom: "Diego Bobadilla",    nomAPI: "D. Bobadilla",      pays: "Panama",           image: "../images/buteur/D. Bobadilla.avif",         buts: 0 },
    { nom: "Boualem Khoukhi",    nomAPI: "B. Khoukhi",        pays: "Qatar",            image: "../images/buteur/B. Khoukhi .webp",          buts: 0 },
    { nom: "Ilias Saibari",      nomAPI: "I. Saibari",        pays: "Maroc",            image: "../images/buteur/I. Saibari.webp",           buts: 0 },
    { nom: "Achraf Hakimi",         nomAPI: "A. Hakimi",            pays: "Maroc",            image: "../images/buteur/Achraf Hakimi.png",              buts: 0 },
    { nom: "Ousmane Dembélé",       nomAPI: "Ousmane Dembélé",      pays: "France",           image: "../images/buteur/Ousmane Dembélé.jpg",            buts: 0 },
    { nom: "Brian Brobbey",         nomAPI: "Brian Brobbey",        pays: "Pays-Bas",         image: "../images/buteur/Brian Brobbey .png",             buts: 0 },
    { nom: "Ismaïla Sarr",          nomAPI: "Ismaïla Sarr",         pays: "Sénégal",          image: "../images/buteur/Ismaïla Sarr.jpg",               buts: 0 },
    { nom: "Matheus Cunha",         nomAPI: "Matheus Cunha",        pays: "Brésil",           image: "../images/buteur/Matheus Cunha.jpg",              buts: 0 },
    { nom: "Anthony Elanga",        nomAPI: "Anthony Elanga",       pays: "Suède",            image: "../images/buteur/Anthony Elanga.jpg",             buts: 0 },
    { nom: "Mikel Oyarzabal",       nomAPI: "Mikel Oyarzabal",      pays: "Espagne",          image: "../images/buteur/Mikel Oyarzabal.jpg",            buts: 0 },
    { nom: "Maximiliano Araújo",    nomAPI: "Maximiliano Araújo",   pays: "Uruguay",          image: "../images/buteur/Maximiliano Araújo.webp",        buts: 0 },
    { nom: "Leandro Trossard",      nomAPI: "Leandro Trossard",     pays: "Belgique",         image: "../images/buteur/Leandro Trossard.jpeg",          buts: 0 },
    { nom: "Alexis Saelemaekers",   nomAPI: "Alexis Saelemaekers",  pays: "Belgique",         image: "../images/buteur/Alexis Saelemaekers.jpg",        buts: 0 },
    { nom: "Kevin De Bruyne",       nomAPI: "Kevin De Bruyne",      pays: "Belgique",         image: "../images/buteur/Kevin De Bruyne.jpeg",           buts: 0 },
    { nom: "Issa Diop",             nomAPI: "Issa Diop",            pays: "France",           image: "../images/buteur/Issa Diop.jpg",                  buts: 0 },
    { nom: "Leroy Sané",            nomAPI: "Leroy Sané",           pays: "Allemagne",        image: "../images/buteur/Leroy Sané.avif",                buts: 0 },
    { nom: "Kai Havertz",           nomAPI: "K. Havertz",           pays: "Allemagne",        image: "../images/buteur/K. Havertz.jpg",                 buts: 0 },
    { nom: "Gabriel Martinelli",    nomAPI: "Gabriel Martinelli",   pays: "Brésil",           image: "../images/buteur/Gabriel Martinelli.png",         buts: 0 },
    { nom: "Virgil van Dijk",       nomAPI: "Virgil van Dijk",      pays: "Pays-Bas",         image: "../images/buteur/Virgil van Dijk.webp",           buts: 0 },
    { nom: "Crysencio Summerville", nomAPI: "Crysencio Summerville",pays: "Pays-Bas",         image: "../images/buteur/Crysencio Summerville.webp",     buts: 0 },
    { nom: "Rafael Leão",           nomAPI: "Rafael Leão",          pays: "Portugal",         image: "../images/buteur/Rafael Leão.jpg",                buts: 0 },
    { nom: "Franck Kessié",         nomAPI: "Franck Kessié",        pays: "Côte d'Ivoire",    image: "../images/buteur/Franck Kessié.jpg",              buts: 0 },
    { nom: "Daichi Kamada",         nomAPI: "Daichi Kamada",        pays: "Japon",            image: "../images/buteur/Daichi Kamada.png",              buts: 0 },
    { nom: "Junya Itō",             nomAPI: "Junya Itō",            pays: "Japon",            image: "../images/buteur/Junya Itō.jpeg",                 buts: 0 },
    { nom: "Désiré Doué",           nomAPI: "Désiré Doué",          pays: "France",           image: "../images/buteur/Désiré Doué.jpg",                buts: 0 },
    { nom: "Wilson Isidor",         nomAPI: "Wilson Isidor",        pays: "France",           image: "../images/buteur/Wilson Isidor.png",              buts: 0 },
    { nom: "Amine Gouiri",          nomAPI: "Amine Gouiri",         pays: "Algérie",          image: "../images/buteur/Amine Gouiri.webp",              buts: 0 },
    { nom: "Leo Østigård",          nomAPI: "Leo Østigård",         pays: "Norvège",          image: "../images/buteur/Leo Østigård.jpeg",              buts: 0 },
    { nom: "Ante Budimir",          nomAPI: "Ante Budimir",         pays: "Croatie",          image: "../images/buteur/Ante Budimir.jpeg",              buts: 0 },
    { nom: "Marcel Sabitzer",       nomAPI: "Marcel Sabitzer",      pays: "Autriche",         image: "../images/buteur/Marcel Sabitzer.webp",           buts: 0 },
    { nom: "Saša Kalajdžić",        nomAPI: "Saša Kalajdžić",       pays: "Autriche",         image: "../images/buteur/Saša Kalajdžić.jpg",             buts: 0 },
    { nom: "Yoane Wissa",           nomAPI: "Yoane Wissa",          pays: "RD Congo",         image: "../images/buteur/Yoane Wissa.png",                buts: 0 },
    { nom: "Pape Guèye",            nomAPI: "Pape Guèye",           pays: "Sénégal",          image: "../images/buteur/Pape Guèye.webp",                buts: 0 },
    { nom: "Yassin Ayari",          nomAPI: "Y. Ayari",             pays: "Suède",            image: "../images/buteur/Y.Ayari.png",                    buts: 0 },
]
