const listeButeurs = [
    { nom: "Cristiano Ronaldo",  nomAPI: "C. Ronaldo",       pays: "Portugal",        image: "../images/CR7.png",                   buts: 0 },
    { nom: "Neymar",             nomAPI: "Neymar",            pays: "Brésil",           image: "../images/Neymar.png",                buts: 0 },
    { nom: "Erling Haaland",     nomAPI: "E. Haaland",        pays: "Norvège",          image: "../images/Haaland.png",               buts: 0 },
    { nom: "Lionel Messi",       nomAPI: "L. Messi",          pays: "Argentine",        image: "../images/Messi.png",                 buts: 0 },
    { nom: "Kylian Mbappé",      nomAPI: "K. Mbappé",         pays: "France",           image: "../images/Mbap.png",                  buts: 0 },
    { nom: "Adam Taggart",       nomAPI: "A. Taggart",        pays: "Australie",        image: "../images/Adam_Taggart.webp",         buts: 0 },
    { nom: "Akram Afif",         nomAPI: "A. Afif",           pays: "Qatar",            image: "../images/Akram_Afif.png",            buts: 0 },
    { nom: "Andrej Kramarić",    nomAPI: "A. Kramarić",       pays: "Croatie",          image: "../images/Andrej_Kramarić.jpeg",      buts: 0 },
    { nom: "Antoine Semenyo",    nomAPI: "A. Semenyo",        pays: "Ghana",            image: "../images/Antoine_Semenyo.png",       buts: 0 },
    { nom: "Breel Embolo",       nomAPI: "Breel Embolo",      pays: "Suisse",           image: "../images/Breel_Embolo.png",          buts: 0 },
    { nom: "Folarin Balogun",    nomAPI: "F. Balogun",        pays: "États-Unis",       image: "../images/F. Balogun.png",            buts: 0 },
    { nom: "Giovanni Reyna",     nomAPI: "G. Reyna",          pays: "États-Unis",       image: "../images/G. Reyna.webp",             buts: 0 },
    { nom: "Cyle Larin",         nomAPI: "C. Larin",          pays: "Canada",           image: "../images/C. Larin.png",              buts: 0 },
    { nom: "Maurício",           nomAPI: "Maurício",          pays: "Paraguay",         image: "../images/Maurício.jpg",              buts: 0 },
    { nom: "Jovo Lukić",         nomAPI: "Jovo Lukić",        pays: "Bosnie-Herzég.",   image: "../images/Jovo Lukić.avif",           buts: 0 },
    { nom: "Cédric Bakambu",     nomAPI: "C. Bakambu",        pays: "RD Congo",         image: "../images/Cédric_Bakambu.jpeg",       buts: 0 },
    { nom: "Chris Wood",         nomAPI: "C. Wood",           pays: "Nouvelle-Zélande", image: "../images/Chris_Wood.png",            buts: 0 },
    { nom: "Christian Pulisic",  nomAPI: "C. Pulisic",        pays: "États-Unis",       image: "../images/Christian_Pulisic.png",     buts: 0 },
    { nom: "Darwin Núñez",       nomAPI: "D. Núñez",          pays: "Uruguay",          image: "../images/Darwin_Núñez.jpeg",         buts: 0 },
    { nom: "Eldor Shomurodov",   nomAPI: "E. Shomurodov",     pays: "Ouzbékistan",      image: "../images/Eldor_Shomurodov.png",      buts: 0 },
    { nom: "Enner Valencia",     nomAPI: "E. Valencia",       pays: "Équateur",         image: "../images/Enner_Valencia.png",        buts: 0 },
    { nom: "Ermedin Demirović",  nomAPI: "E. Demirović",      pays: "Bosnie",           image: "../images/Ermedin_Demirović.webp",    buts: 0 },
    { nom: "Florian Wirtz",      nomAPI: "F. Wirtz",          pays: "Allemagne",        image: "../images/Florian_Wirtz.png",         buts: 0 },
    { nom: "Frantzdy Pierrot",   nomAPI: "F. Pierrot",        pays: "Haïti",            image: "../images/Frantzdy_Pierrot.jpg",      buts: 0 },
    { nom: "Harry Kane",         nomAPI: "H. Kane",           pays: "Angleterre",       image: "../images/Harry_Kane.png",            buts: 0 },
    { nom: "Hwang In-beom",      nomAPI: "I.B. Hwang",     pays: "Corée du Sud",     image: "../images/Hwang_In-beom.webp",        buts: 0 },
    { nom: "Henry Martín",       nomAPI: "H. Martín",         pays: "Mexique",          image: "../images/Henry_Martín.png",          buts: 0 },
    { nom: "Ismael Díaz",        nomAPI: "I. Díaz",           pays: "Panama",           image: "../images/Ismael_Díaz.webp",          buts: 0 },
    { nom: "Kaoru Mitoma",       nomAPI: "K. Mitoma",         pays: "Japon",            image: "../images/Kaoru_Mitoma.png",          buts: 0 },
    { nom: "Kenan Yıldız",       nomAPI: "K. Yıldız",         pays: "Turquie",          image: "../images/Kenan_Yıldız.jpeg",         buts: 0 },
    { nom: "Ladislav Krejčí",    nomAPI: "L. Krejčí",         pays: "Rép. tchèque",     image: "../images/L.Krejčí.png",              buts: 0 },
    { nom: "Lamine Yamal",       nomAPI: "L. Yamal",          pays: "Espagne",          image: "../images/Lamine_Yamal.png",          buts: 0 },
    { nom: "Lautaro Martínez",   nomAPI: "L. Martínez",       pays: "Argentine",        image: "../images/Lautaro_Martínez.png",      buts: 0 },
    { nom: "Lawrence Shankland", nomAPI: "L. Shankland",      pays: "Écosse",           image: "../images/Lawrence_Shankland.png",    buts: 0 },
    { nom: "Leandro Bacuna",     nomAPI: "L. Bacuna",         pays: "Curaçao",          image: "../images/Leandro_Bacuna.jpg",        buts: 0 },
    { nom: "Luis Díaz",          nomAPI: "L. Díaz",           pays: "Colombie",         image: "../images/Luis_Díaz.avif",            buts: 0 },
    { nom: "Marko Arnautović",   nomAPI: "M. Arnautović",     pays: "Autriche",         image: "../images/Marko_Arnautović.png",      buts: 0 },
    { nom: "Mehdi Taremi",       nomAPI: "M. Taremi",         pays: "Iran",             image: "../images/Mehdi_Taremi.png",          buts: 0 },
    { nom: "Miguel Almirón",     nomAPI: "M. Almirón",        pays: "Paraguay",         image: "../images/Miguel_Almirón.png",        buts: 0 },
    { nom: "Mohamed Salah",      nomAPI: "M. Salah",          pays: "Égypte",           image: "../images/Mohamed_Salah.png",         buts: 0 },
    { nom: "Mohanad Ali",        nomAPI: "Mohanad Ali",       pays: "Irak",             image: "../images/Mohanad_Ali.jpg",           buts: 0 },
    { nom: "Mousa Al-Tamari",    nomAPI: "M. Al-Tamari",      pays: "Jordanie",         image: "../images/Mousa_Al-Tamari.png",       buts: 0 },
    { nom: "Lucas Paquetá",      nomAPI: "L. Paquetá",        pays: "Brésil",           image: "../images/Paquetarmv.png",            buts: 0 },
    { nom: "Patrik Schick",      nomAPI: "P. Schick",         pays: "Rép. tchèque",     image: "../images/Patrik_Schick.png",         buts: 0 },
    { nom: "Percy Tau",          nomAPI: "P. Tau",            pays: "Afrique du Sud",   image: "../images/Percy_Tau.jpeg",            buts: 0 },
    { nom: "Julián Quiñones",    nomAPI: "J. Quiñones",       pays: "Mexique",          image: "../images/J. Quiñones.png",           buts: 0 },
    { nom: "Raúl Jiménez",       nomAPI: "R. Jiménez",        pays: "Mexique",          image: "../images/Raúl_Jiménez.png",          buts: 0 },
    { nom: "Riyad Mahrez",       nomAPI: "R. Mahrez",         pays: "Algérie",          image: "../images/Riyad_Mahrez.png",          buts: 0 },
    { nom: "Romelu Lukaku",      nomAPI: "R. Lukaku",         pays: "Belgique",         image: "../images/Romelu_Lukaku.png",         buts: 0 },
    { nom: "Ryan Mendes",        nomAPI: "R. Mendes",         pays: "Cap-Vert",         image: "../images/Ryan_Mendes.webp",          buts: 0 },
    { nom: "Sadio Mané",         nomAPI: "S. Mané",           pays: "Sénégal",          image: "../images/Sadio_Mané.png",            buts: 0 },
    { nom: "Salem Al-Dawsari",   nomAPI: "S. Al-Dawsari",     pays: "Arabie Saoudite",  image: "../images/Salem_Al-Dawsari.png",      buts: 0 },
    { nom: "Sébastien Haller",   nomAPI: "S. Haller",         pays: "Côte d'Ivoire",    image: "../images/Sébastien_Haller.png",      buts: 0 },
    { nom: "Oh Hyeon-gyu",       nomAPI: "H.G. Oh",      pays: "Corée du Sud",     image: "../images/oh hyeon-gyu.webp",         buts: 0 },
    { nom: "Son Heung-min",      nomAPI: "H.M Son",     pays: "Corée du Sud",     image: "../images/Son_Heung-min.png",         buts: 0 },
    { nom: "Viktor Gyökeres",    nomAPI: "V. Gyökeres",       pays: "Suède",            image: "../images/Viktor_Gyökeres.png",       buts: 0 },
    { nom: "Vinicius Jr",        nomAPI: "Vinicius Jr",       pays: "Brésil",           image: "../images/Vinicius_Jr.png",           buts: 0 },
    { nom: "Youssef En-Nesyri",  nomAPI: "Y. En-Nesyri",      pays: "Maroc",            image: "../images/Youssef_En-Nesyri.png",     buts: 0 },
    { nom: "Youssef Msakni",     nomAPI: "Y. Msakni",         pays: "Tunisie",          image: "../images/Youssef_Msakni.webp",       buts: 0 },
    { nom: "Jonathan David",     nomAPI: "J. David",          pays: "Canada",           image: "../images/Jonathan_David.png",        buts: 0 },
    { nom: "Cody Gakpo",         nomAPI: "C. Gakpo",          pays: "Pays-Bas",         image: "../images/Cody_Gakpo.png",            buts: 0 },
]
