const effectifs = {
    "Algeria": {
        entraineur: "Vladimir Petkovic",
        titres: [],
        participations: [
            { annee: 1982, phase: "R16" },
            { annee: 1986, phase: "1er tour" },
            { annee: 2010, phase: "1er tour" },
            { annee: 2014, phase: "R16" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Rais M'Bolhi", poste: "Gardien", club: "Al-Ettifaq" },
            { nom: "Alexandre Oukidja", poste: "Gardien", club: "Metz" },
            { nom: "Aïssa Mandi", poste: "Défenseur", club: "Villarreal" },
            { nom: "Ramy Bensebaini", poste: "Défenseur", club: "Borussia Dortmund" },
            { nom: "Djamel Benlamri", poste: "Défenseur", club: "Lyon" },
            { nom: "Youcef Atal", poste: "Défenseur", club: "Nice" },
            { nom: "Mehdi Zerkane", poste: "Milieu", club: "Sharjah FC" },
            { nom: "Ramiz Zerrouki", poste: "Milieu", club: "Twente" },
            { nom: "Saphir Taïder", poste: "Milieu", club: "Montréal" },
            { nom: "Ismael Bennacer", poste: "Milieu", club: "AC Milan" },
            { nom: "Adam Ounas", poste: "Attaquant", club: "Lille" },
            { nom: "Baghdad Bounedjah", poste: "Attaquant", club: "Al-Sadd" },
            { nom: "Islam Slimani", poste: "Attaquant", club: "Brest" },
            { nom: "Youcef Belaïli", poste: "Attaquant", club: "Qarabağ" },
            { nom: "Andy Delort", poste: "Attaquant", club: "Nice" }
        ]
    },
    "Argentina": {
        entraineur: "Lionel Scaloni",
        titres: ["Champion du Monde 1978", "Champion du Monde 1986", "Champion du Monde 2022"],
        participations: [
            { annee: 1930, phase: "Finaliste" },
            { annee: 1934, phase: "1er tour" },
            { annee: 1958, phase: "1er tour" },
            { annee: 1962, phase: "1er tour" },
            { annee: 1966, phase: "QF" },
            { annee: 1974, phase: "2e tour" },
            { annee: 1978, phase: "Vainqueur" },
            { annee: 1982, phase: "2e tour" },
            { annee: 1986, phase: "Vainqueur" },
            { annee: 1990, phase: "Finaliste" },
            { annee: 1994, phase: "R16" },
            { annee: 1998, phase: "QF" },
            { annee: 2002, phase: "1er tour" },
            { annee: 2006, phase: "QF" },
            { annee: 2010, phase: "QF" },
            { annee: 2014, phase: "Finaliste" },
            { annee: 2018, phase: "R16" },
            { annee: 2022, phase: "Vainqueur" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Emiliano Martínez", poste: "Gardien", club: "Aston Villa" },
            { nom: "Franco Armani", poste: "Gardien", club: "River Plate" },
            { nom: "Nahuel Molina", poste: "Défenseur", club: "Atletico Madrid" },
            { nom: "Gonzalo Montiel", poste: "Défenseur", club: "Nottingham Forest" },
            { nom: "Cristian Romero", poste: "Défenseur", club: "Tottenham" },
            { nom: "Lisandro Martínez", poste: "Défenseur", club: "Manchester United" },
            { nom: "Nicolás Otamendi", poste: "Défenseur", club: "Benfica" },
            { nom: "Nicolás Tagliafico", poste: "Défenseur", club: "Lyon" },
            { nom: "Rodrigo De Paul", poste: "Milieu", club: "Atletico Madrid" },
            { nom: "Enzo Fernández", poste: "Milieu", club: "Chelsea" },
            { nom: "Leandro Paredes", poste: "Milieu", club: "Roma" },
            { nom: "Alexis Mac Allister", poste: "Milieu", club: "Liverpool" },
            { nom: "Lionel Messi", poste: "Attaquant", club: "Inter Miami" },
            { nom: "Ángel Di María", poste: "Attaquant", club: "Benfica" },
            { nom: "Lautaro Martínez", poste: "Attaquant", club: "Inter Milan" },
            { nom: "Julián Álvarez", poste: "Attaquant", club: "Atletico Madrid" },
            { nom: "Paulo Dybala", poste: "Attaquant", club: "Roma" }
        ]
    },
    "Australia": {
        entraineur: "Tony Popovic",
        titres: [],
        participations: [
            { annee: 1974, phase: "1er tour" },
            { annee: 2006, phase: "R16" },
            { annee: 2010, phase: "1er tour" },
            { annee: 2014, phase: "1er tour" },
            { annee: 2018, phase: "1er tour" },
            { annee: 2022, phase: "R16" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Mat Ryan", poste: "Gardien", club: "Real Sociedad" },
            { nom: "Danny Vukovic", poste: "Gardien", club: "Genk" },
            { nom: "Milos Degenek", poste: "Défenseur", club: "Columbus Crew" },
            { nom: "Aziz Behich", poste: "Défenseur", club: "Dundee United" },
            { nom: "Harry Souttar", poste: "Défenseur", club: "Leicester City" },
            { nom: "Kye Rowles", poste: "Défenseur", club: "Hearts" },
            { nom: "Joel King", poste: "Défenseur", club: "Odense BK" },
            { nom: "Riley McGree", poste: "Milieu", club: "Middlesbrough" },
            { nom: "Aaron Mooy", poste: "Milieu", club: "Celtic" },
            { nom: "Jackson Irvine", poste: "Milieu", club: "St. Pauli" },
            { nom: "Keanu Baccus", poste: "Milieu", club: "St. Mirren" },
            { nom: "Mathew Leckie", poste: "Attaquant", club: "Melbourne City" },
            { nom: "Martin Boyle", poste: "Attaquant", club: "Panathinaikos" },
            { nom: "Mitchell Duke", poste: "Attaquant", club: "Fagiano Okayama" },
            { nom: "Craig Goodwin", poste: "Attaquant", club: "Adelaide United" }
        ]
    },
    "Austria": {
        entraineur: "Ralf Rangnick",
        titres: [],
        participations: [
            { annee: 1934, phase: "4e place" },
            { annee: 1954, phase: "3e place" },
            { annee: 1958, phase: "1er tour" },
            { annee: 1978, phase: "2e tour" },
            { annee: 1982, phase: "2e tour" },
            { annee: 1990, phase: "1er tour" },
            { annee: 1998, phase: "1er tour" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Patrick Pentz", poste: "Gardien", club: "Bayer Leverkusen" },
            { nom: "Heinz Lindner", poste: "Gardien", club: "Grasshopper" },
            { nom: "Stefan Posch", poste: "Défenseur", club: "Bologna" },
            { nom: "Philipp Mwene", poste: "Défenseur", club: "Mainz" },
            { nom: "Kevin Danso", poste: "Défenseur", club: "RC Lens" },
            { nom: "Maximilian Wöber", poste: "Défenseur", club: "Borussia Mönchengladbach" },
            { nom: "Phillipp Lienhart", poste: "Défenseur", club: "Freiburg" },
            { nom: "Florian Grillitsch", poste: "Milieu", club: "Nice" },
            { nom: "Nicolas Seiwald", poste: "Milieu", club: "RB Leipzig" },
            { nom: "Konrad Laimer", poste: "Milieu", club: "Bayern Munich" },
            { nom: "Christoph Baumgartner", poste: "Milieu", club: "RB Leipzig" },
            { nom: "Marcel Sabitzer", poste: "Milieu", club: "Borussia Dortmund" },
            { nom: "Marko Arnautovic", poste: "Attaquant", club: "Inter Milan" },
            { nom: "Michael Gregoritsch", poste: "Attaquant", club: "Freiburg" },
            { nom: "Patrick Wimmer", poste: "Attaquant", club: "Wolfsburg" },
            { nom: "Florian Kainz", poste: "Attaquant", club: "FC Cologne" }
        ]
    },
    "Belgium": {
        entraineur: "Domenico Tedesco",
        titres: [],
        participations: [
            { annee: 1930, phase: "1er tour" },
            { annee: 1934, phase: "1er tour" },
            { annee: 1938, phase: "1er tour" },
            { annee: 1954, phase: "1er tour" },
            { annee: 1970, phase: "1er tour" },
            { annee: 1982, phase: "2e tour" },
            { annee: 1986, phase: "4e place" },
            { annee: 1990, phase: "R16" },
            { annee: 1994, phase: "R16" },
            { annee: 1998, phase: "1er tour" },
            { annee: 2002, phase: "R16" },
            { annee: 2014, phase: "QF" },
            { annee: 2018, phase: "3e place" },
            { annee: 2022, phase: "1er tour" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Koen Casteels", poste: "Gardien", club: "VfL Wolfsburg" },
            { nom: "Thomas Kaminski", poste: "Gardien", club: "Luton Town" },
            { nom: "Timothy Castagne", poste: "Défenseur", club: "Fulham" },
            { nom: "Thomas Meunier", poste: "Défenseur", club: "Trabzonspor" },
            { nom: "Wout Faes", poste: "Défenseur", club: "Leicester City" },
            { nom: "Arthur Theate", poste: "Défenseur", club: "Rennes" },
            { nom: "Jan Vertonghen", poste: "Défenseur", club: "RSC Anderlecht" },
            { nom: "Axel Witsel", poste: "Milieu", club: "Atletico Madrid" },
            { nom: "Kevin De Bruyne", poste: "Milieu", club: "Manchester City" },
            { nom: "Youri Tielemans", poste: "Milieu", club: "Aston Villa" },
            { nom: "Amadou Onana", poste: "Milieu", club: "Aston Villa" },
            { nom: "Leandro Trossard", poste: "Attaquant", club: "Arsenal" },
            { nom: "Romelu Lukaku", poste: "Attaquant", club: "Roma" },
            { nom: "Dodi Lukebakio", poste: "Attaquant", club: "Séville" },
            { nom: "Lois Openda", poste: "Attaquant", club: "RB Leipzig" },
            { nom: "Johan Bakayoko", poste: "Attaquant", club: "PSV Eindhoven" }
        ]
    },
    "Bosnia and Herzegovina": {
        entraineur: "Sergej Barbarez",
        titres: [],
        participations: [
            { annee: 2014, phase: "1er tour" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Kenan Piric", poste: "Gardien", club: "Hammarby" },
            { nom: "Nikola Vasilj", poste: "Gardien", club: "St. Pauli" },
            { nom: "Sead Kolašinac", poste: "Défenseur", club: "Marseille" },
            { nom: "Ognjen Vranješ", poste: "Défenseur", club: "Lechia Gdańsk" },
            { nom: "Ermin Bičakčić", poste: "Défenseur", club: "Hoffenheim" },
            { nom: "Darko Todorović", poste: "Défenseur", club: "Partizan" },
            { nom: "Miralem Pjanić", poste: "Milieu", club: "Sharjah FC" },
            { nom: "Haris Hajradinović", poste: "Milieu", club: "Legia Warsaw" },
            { nom: "Armin Hodžić", poste: "Milieu", club: "Lechia Gdańsk" },
            { nom: "Rustem Krpić", poste: "Milieu", club: "NK Osijek" },
            { nom: "Edin Džeko", poste: "Attaquant", club: "Fenerbahçe" },
            { nom: "Anel Ahmedhodžić", poste: "Attaquant", club: "Sheffield United" },
            { nom: "Ermedin Demirović", poste: "Attaquant", club: "Stuttgart" },
            { nom: "Dario Šarić", poste: "Attaquant", club: "Almeria" }
        ]
    },
    "Brazil": {
        entraineur: "Dorival Júnior",
        titres: ["Champion du Monde 1958", "Champion du Monde 1962", "Champion du Monde 1970", "Champion du Monde 1994", "Champion du Monde 2002"],
        participations: [
            { annee: 1930, phase: "SF" },
            { annee: 1934, phase: "1er tour" },
            { annee: 1938, phase: "3e place" },
            { annee: 1950, phase: "Finaliste" },
            { annee: 1954, phase: "QF" },
            { annee: 1958, phase: "Vainqueur" },
            { annee: 1962, phase: "Vainqueur" },
            { annee: 1966, phase: "1er tour" },
            { annee: 1970, phase: "Vainqueur" },
            { annee: 1974, phase: "4e place" },
            { annee: 1978, phase: "3e place" },
            { annee: 1982, phase: "2e tour" },
            { annee: 1986, phase: "QF" },
            { annee: 1990, phase: "R16" },
            { annee: 1994, phase: "Vainqueur" },
            { annee: 1998, phase: "Finaliste" },
            { annee: 2002, phase: "Vainqueur" },
            { annee: 2006, phase: "QF" },
            { annee: 2010, phase: "QF" },
            { annee: 2014, phase: "4e place" },
            { annee: 2018, phase: "QF" },
            { annee: 2022, phase: "QF" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Alisson Becker", poste: "Gardien", club: "Liverpool" },
            { nom: "Ederson", poste: "Gardien", club: "Manchester City" },
            { nom: "Weverton", poste: "Gardien", club: "Palmeiras" },
            { nom: "Danilo", poste: "Défenseur", club: "Juventus" },
            { nom: "Éder Militão", poste: "Défenseur", club: "Real Madrid" },
            { nom: "Marquinhos", poste: "Défenseur", club: "Paris SG" },
            { nom: "Gabriel Magalhães", poste: "Défenseur", club: "Arsenal" },
            { nom: "Guilherme Arana", poste: "Défenseur", club: "Atlético Mineiro" },
            { nom: "Casemiro", poste: "Milieu", club: "Manchester United" },
            { nom: "Bruno Guimarães", poste: "Milieu", club: "Newcastle" },
            { nom: "Lucas Paquetá", poste: "Milieu", club: "West Ham" },
            { nom: "Gerson", poste: "Milieu", club: "Flamengo" },
            { nom: "Vinícius Jr.", poste: "Attaquant", club: "Real Madrid" },
            { nom: "Rodrygo", poste: "Attaquant", club: "Real Madrid" },
            { nom: "Gabriel Martinelli", poste: "Attaquant", club: "Arsenal" },
            { nom: "Raphinha", poste: "Attaquant", club: "FC Barcelone" },
            { nom: "Endrick", poste: "Attaquant", club: "Real Madrid" },
            { nom: "Gabriel Barbosa", poste: "Attaquant", club: "Flamengo" }
        ]
    },
    "Canada": {
        entraineur: "Jesse Marsch",
        titres: [],
        participations: [
            { annee: 1986, phase: "1er tour" },
            { annee: 2022, phase: "1er tour" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Maxime Crépeau", poste: "Gardien", club: "LA Galaxy" },
            { nom: "Milan Borjan", poste: "Gardien", club: "Red Star Belgrade" },
            { nom: "Richie Laryea", poste: "Défenseur", club: "Nottingham Forest" },
            { nom: "Alistair Johnston", poste: "Défenseur", club: "Celtic" },
            { nom: "Kamal Miller", poste: "Défenseur", club: "Orlando City" },
            { nom: "Steven Vitória", poste: "Défenseur", club: "Marítimo" },
            { nom: "Derek Cornelius", poste: "Défenseur", club: "Vancouver Whitecaps" },
            { nom: "Atiba Hutchinson", poste: "Milieu", club: "Beşiktaş" },
            { nom: "Stephen Eustáquio", poste: "Milieu", club: "FC Porto" },
            { nom: "Liam Millar", poste: "Milieu", club: "FC Bâle" },
            { nom: "Jonathan Osorio", poste: "Milieu", club: "Toronto FC" },
            { nom: "Alphonso Davies", poste: "Attaquant", club: "Bayern Munich" },
            { nom: "Jonathan David", poste: "Attaquant", club: "Lille" },
            { nom: "Cyle Larin", poste: "Attaquant", club: "Majorque" },
            { nom: "Tajon Buchanan", poste: "Attaquant", club: "Club Brugge" },
            { nom: "Lucas Cavallini", poste: "Attaquant", club: "Vancouver Whitecaps" }
        ]
    },
    "Cape Verde": {
        entraineur: "Pedro Brito",
        titres: [],
        participations: [
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Vozinha", poste: "Gardien", club: "Celta Vigo" },
            { nom: "Fali Candé", poste: "Gardien", club: "Benfica B" },
            { nom: "Roberto Lopes", poste: "Défenseur", club: "Shamrock Rovers" },
            { nom: "Stopira", poste: "Défenseur", club: "Servette" },
            { nom: "Diney", poste: "Défenseur", club: "PAOK" },
            { nom: "Dylan Tavares", poste: "Défenseur", club: "Benfica B" },
            { nom: "Kenny Rocha Santos", poste: "Milieu", club: "Santos FC" },
            { nom: "Jamiro Monteiro", poste: "Milieu", club: "Club Brugge" },
            { nom: "Ryan Mendes", poste: "Milieu", club: "Lille" },
            { nom: "Garry Rodrigues", poste: "Attaquant", club: "Galatasaray" },
            { nom: "Djaniny", poste: "Attaquant", club: "Al-Ahli" },
            { nom: "Julio Tavares", poste: "Attaquant", club: "Al-Fateh" }
        ]
    },
    "Colombia": {
        entraineur: "Néstor Lorenzo",
        titres: [],
        participations: [
            { annee: 1962, phase: "1er tour" },
            { annee: 1990, phase: "R16" },
            { annee: 1994, phase: "1er tour" },
            { annee: 1998, phase: "1er tour" },
            { annee: 2014, phase: "QF" },
            { annee: 2018, phase: "R16" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "David Ospina", poste: "Gardien", club: "Al-Qadsiah" },
            { nom: "Camilo Vargas", poste: "Gardien", club: "Atlas" },
            { nom: "Santiago Arias", poste: "Défenseur", club: "Bayer Leverkusen" },
            { nom: "Dávinson Sánchez", poste: "Défenseur", club: "Galatasaray" },
            { nom: "Yerry Mina", poste: "Défenseur", club: "Fiorentina" },
            { nom: "William Tesillo", poste: "Défenseur", club: "Club León" },
            { nom: "Johan Mojica", poste: "Défenseur", club: "Villarreal" },
            { nom: "Wilmar Barrios", poste: "Milieu", club: "Zenit" },
            { nom: "Mateus Uribe", poste: "Milieu", club: "FC Porto" },
            { nom: "Juan Cuadrado", poste: "Milieu", club: "Inter Milan" },
            { nom: "James Rodríguez", poste: "Milieu", club: "Rayo Vallecano" },
            { nom: "Richard Ríos", poste: "Milieu", club: "Palmeiras" },
            { nom: "Luis Díaz", poste: "Attaquant", club: "Liverpool" },
            { nom: "Jhon Durán", poste: "Attaquant", club: "Aston Villa" },
            { nom: "Rafael Santos Borré", poste: "Attaquant", club: "Eintracht Frankfurt" },
            { nom: "Jhon Córdoba", poste: "Attaquant", club: "Krasnodar" }
        ]
    },
    "Croatia": {
        entraineur: "Zlatko Dalić",
        titres: [],
        participations: [
            { annee: 1998, phase: "3e place" },
            { annee: 2002, phase: "1er tour" },
            { annee: 2006, phase: "1er tour" },
            { annee: 2014, phase: "1er tour" },
            { annee: 2018, phase: "Finaliste" },
            { annee: 2022, phase: "3e place" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Dominik Livaković", poste: "Gardien", club: "Fenerbahçe" },
            { nom: "Ivo Grbić", poste: "Gardien", club: "Atletico Madrid" },
            { nom: "Josip Juranović", poste: "Défenseur", club: "Union Berlin" },
            { nom: "Borna Sosa", poste: "Défenseur", club: "Stuttgart" },
            { nom: "Joško Gvardiol", poste: "Défenseur", club: "Manchester City" },
            { nom: "Duje Ćaleta-Car", poste: "Défenseur", club: "Southampton" },
            { nom: "Josip Šutalo", poste: "Défenseur", club: "Ajax" },
            { nom: "Luka Modrić", poste: "Milieu", club: "Real Madrid" },
            { nom: "Mateo Kovačić", poste: "Milieu", club: "Manchester City" },
            { nom: "Marcelo Brozović", poste: "Milieu", club: "Al-Nassr" },
            { nom: "Mario Pašalić", poste: "Milieu", club: "Atalanta" },
            { nom: "Lovro Majer", poste: "Milieu", club: "Real Madrid" },
            { nom: "Ivan Perišić", poste: "Attaquant", club: "Hajduk Split" },
            { nom: "Ante Budimir", poste: "Attaquant", club: "Osasuna" },
            { nom: "Andrej Kramarić", poste: "Attaquant", club: "Hoffenheim" },
            { nom: "Bruno Petković", poste: "Attaquant", club: "Dinamo Zagreb" }
        ]
    },
    "Curaçao": {
        entraineur: "Remko Bicentini",
        titres: [],
        participations: [
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Eloy Room", poste: "Gardien", club: "Columbus Crew" },
            { nom: "Gianni Zuiverloon", poste: "Défenseur", club: "Mjällby" },
            { nom: "Cuco Martina", poste: "Défenseur", club: "Stoke City" },
            { nom: "Rangelo Janga", poste: "Défenseur", club: "AIK" },
            { nom: "Leandro Bacuna", poste: "Milieu", club: "Cardiff City" },
            { nom: "Jair Marrufo", poste: "Milieu", club: "ADO Den Haag" },
            { nom: "Gevaro Nepomuceno", poste: "Milieu", club: "Antalyaspor" },
            { nom: "Sheraldo Becker", poste: "Attaquant", club: "Union Berlin" },
            { nom: "Chedrick Apai", poste: "Attaquant", club: "Gençlerbirliği" },
            { nom: "Jafar Arias", poste: "Attaquant", club: "Hellas Vérone" }
        ]
    },
    "Czech Republic": {
        entraineur: "Ivan Hašek",
        titres: [],
        participations: [
            { annee: 2006, phase: "1er tour" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Jiří Staněk", poste: "Gardien", club: "Séville" },
            { nom: "Tomáš Vaclík", poste: "Gardien", club: "Olympiakos" },
            { nom: "Vladimir Coufal", poste: "Défenseur", club: "West Ham" },
            { nom: "Tomáš Souček", poste: "Milieu", club: "West Ham" },
            { nom: "Jakub Jankto", poste: "Milieu", club: "Sparta Prague" },
            { nom: "Lukáš Provod", poste: "Milieu", club: "Sparta Prague" },
            { nom: "Marek Soucek", poste: "Milieu", club: "Twente" },
            { nom: "Antonín Barák", poste: "Milieu", club: "Fiorentina" },
            { nom: "Patrik Schick", poste: "Attaquant", club: "Bayer Leverkusen" },
            { nom: "Adam Hložek", poste: "Attaquant", club: "Bayer Leverkusen" },
            { nom: "Ondřej Lingr", poste: "Attaquant", club: "Feyenoord" },
            { nom: "Jan Kuchta", poste: "Attaquant", club: "Sparta Prague" }
        ]
    },
    "Democratic Republic of the Congo": {
        entraineur: "Sébastien Desabre",
        titres: [],
        participations: [
            { annee: 1974, phase: "1er tour" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Lionel Mpasi", poste: "Gardien", club: "Malines" },
            { nom: "Joël Kiassumbua", poste: "Gardien", club: "Beerschot" },
            { nom: "Chancel Mbemba", poste: "Défenseur", club: "Marseille" },
            { nom: "Nico Isimat-Mirin", poste: "Défenseur", club: "Toulouse" },
            { nom: "Ngonda Muzinga", poste: "Défenseur", club: "Charleroi" },
            { nom: "Arthur Masuaku", poste: "Défenseur", club: "Besiktas" },
            { nom: "Yoane Wissa", poste: "Milieu", club: "Brentford" },
            { nom: "Samuel Bastien", poste: "Milieu", club: "Standard Liège" },
            { nom: "Cédric Bakambu", poste: "Attaquant", club: "Marseille" },
            { nom: "Dodi Lukebakio", poste: "Attaquant", club: "Séville" },
            { nom: "Britt Assombalonga", poste: "Attaquant", club: "Adana Demirspor" },
            { nom: "Paul-José Mpoku", poste: "Attaquant", club: "Standard Liège" }
        ]
    },
    "Ecuador": {
        entraineur: "Sebastián Beccacece",
        titres: [],
        participations: [
            { annee: 2002, phase: "1er tour" },
            { annee: 2006, phase: "R16" },
            { annee: 2014, phase: "1er tour" },
            { annee: 2022, phase: "1er tour" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Hernán Galíndez", poste: "Gardien", club: "Aucas" },
            { nom: "Moisés Ramírez", poste: "Gardien", club: "Independiente del Valle" },
            { nom: "Piero Hincapié", poste: "Défenseur", club: "Bayer Leverkusen" },
            { nom: "Robert Arboleda", poste: "Défenseur", club: "São Paulo" },
            { nom: "Félix Torres", poste: "Défenseur", club: "Santos Laguna" },
            { nom: "Byron Castillo", poste: "Défenseur", club: "Liga de Quito" },
            { nom: "Pervis Estupiñán", poste: "Défenseur", club: "Brighton" },
            { nom: "José Cifuentes", poste: "Milieu", club: "Los Angeles FC" },
            { nom: "Carlos Gruezo", poste: "Milieu", club: "Augsburg" },
            { nom: "Romario Ibarra", poste: "Milieu", club: "Pachuca" },
            { nom: "Moisés Caicedo", poste: "Milieu", club: "Chelsea" },
            { nom: "Gonzalo Plata", poste: "Attaquant", club: "Valladolid" },
            { nom: "Enner Valencia", poste: "Attaquant", club: "Fenerbahçe" },
            { nom: "Michael Estrada", poste: "Attaquant", club: "Cruz Azul" },
            { nom: "Jeremy Sarmiento", poste: "Attaquant", club: "Brighton" }
        ]
    },
    "Egypt": {
        entraineur: "Hossam Hassan",
        titres: [],
        participations: [
            { annee: 1934, phase: "1er tour" },
            { annee: 1990, phase: "1er tour" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Mohamed El Shenawy", poste: "Gardien", club: "Al-Ahly" },
            { nom: "Ahmed El Shenawy", poste: "Gardien", club: "Zamalek" },
            { nom: "Ahmed Hegazi", poste: "Défenseur", club: "Al-Ittihad" },
            { nom: "Omar Kamal", poste: "Défenseur", club: "Al-Ahly" },
            { nom: "Mohamed Abdelmonem", poste: "Défenseur", club: "Al-Ahly" },
            { nom: "Mahmoud Hamdy", poste: "Défenseur", club: "Zamalek" },
            { nom: "Ahmed Sayed Zizo", poste: "Milieu", club: "Zamalek" },
            { nom: "Tarek Hamed", poste: "Milieu", club: "Al-Ahly" },
            { nom: "Mohamed Elneny", poste: "Milieu", club: "Arsenal" },
            { nom: "Emam Ashour", poste: "Milieu", club: "Zamalek" },
            { nom: "Mohamed Salah", poste: "Attaquant", club: "Liverpool" },
            { nom: "Mostafa Mohamed", poste: "Attaquant", club: "Nantes" },
            { nom: "Omar Marmoush", poste: "Attaquant", club: "Manchester City" },
            { nom: "Ramadan Sobhi", poste: "Attaquant", club: "Al-Ahly" }
        ]
    },
    "England": {
        entraineur: "Lee Carsley",
        titres: ["Champion du Monde 1966"],
        participations: [
            { annee: 1950, phase: "1er tour" },
            { annee: 1954, phase: "QF" },
            { annee: 1958, phase: "1er tour" },
            { annee: 1962, phase: "QF" },
            { annee: 1966, phase: "Vainqueur" },
            { annee: 1970, phase: "QF" },
            { annee: 1982, phase: "2e tour" },
            { annee: 1986, phase: "QF" },
            { annee: 1990, phase: "4e place" },
            { annee: 1998, phase: "R16" },
            { annee: 2002, phase: "QF" },
            { annee: 2006, phase: "QF" },
            { annee: 2010, phase: "R16" },
            { annee: 2014, phase: "1er tour" },
            { annee: 2018, phase: "4e place" },
            { annee: 2022, phase: "QF" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Jordan Pickford", poste: "Gardien", club: "Everton" },
            { nom: "Aaron Ramsdale", poste: "Gardien", club: "Southampton" },
            { nom: "Dean Henderson", poste: "Gardien", club: "Crystal Palace" },
            { nom: "Kyle Walker", poste: "Défenseur", club: "Manchester City" },
            { nom: "Reece James", poste: "Défenseur", club: "Chelsea" },
            { nom: "Harry Maguire", poste: "Défenseur", club: "Manchester United" },
            { nom: "John Stones", poste: "Défenseur", club: "Manchester City" },
            { nom: "Marc Guehi", poste: "Défenseur", club: "Crystal Palace" },
            { nom: "Luke Shaw", poste: "Défenseur", club: "Manchester United" },
            { nom: "Kieran Trippier", poste: "Défenseur", club: "Newcastle" },
            { nom: "Declan Rice", poste: "Milieu", club: "Arsenal" },
            { nom: "Jude Bellingham", poste: "Milieu", club: "Real Madrid" },
            { nom: "Kobbie Mainoo", poste: "Milieu", club: "Manchester United" },
            { nom: "Conor Gallagher", poste: "Milieu", club: "Atletico Madrid" },
            { nom: "Phil Foden", poste: "Milieu", club: "Manchester City" },
            { nom: "Harry Kane", poste: "Attaquant", club: "Bayern Munich" },
            { nom: "Marcus Rashford", poste: "Attaquant", club: "Aston Villa" },
            { nom: "Bukayo Saka", poste: "Attaquant", club: "Arsenal" },
            { nom: "Ollie Watkins", poste: "Attaquant", club: "Aston Villa" },
            { nom: "Cole Palmer", poste: "Attaquant", club: "Chelsea" },
            { nom: "Anthony Gordon", poste: "Attaquant", club: "Newcastle" }
        ]
    },
    "France": {
        entraineur: "Didier Deschamps",
        titres: ["Champion du Monde 1998", "Champion du Monde 2018"],
        participations: [
            { annee: 1930, phase: "1er tour" },
            { annee: 1934, phase: "1er tour" },
            { annee: 1938, phase: "QF" },
            { annee: 1954, phase: "1er tour" },
            { annee: 1958, phase: "3e place" },
            { annee: 1966, phase: "1er tour" },
            { annee: 1978, phase: "1er tour" },
            { annee: 1982, phase: "4e place" },
            { annee: 1986, phase: "3e place" },
            { annee: 1998, phase: "Vainqueur" },
            { annee: 2002, phase: "1er tour" },
            { annee: 2006, phase: "Finaliste" },
            { annee: 2010, phase: "1er tour" },
            { annee: 2014, phase: "QF" },
            { annee: 2018, phase: "Vainqueur" },
            { annee: 2022, phase: "Finaliste" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Mike Maignan", poste: "Gardien", club: "AC Milan" },
            { nom: "Robin Risser Birckel", poste: "Gardien", club: "RC Strasbourg" },
            { nom: "Brice Samba", poste: "Gardien", club: "RC Lens" },
            { nom: "Lucas Digne", poste: "Défenseur", club: "Aston Villa" },
            { nom: "Malo Gusto", poste: "Défenseur", club: "Chelsea" },
            { nom: "Lucas Hernandez", poste: "Défenseur", club: "Paris SG" },
            { nom: "Théo Hernandez", poste: "Défenseur", club: "AC Milan" },
            { nom: "Ibrahima Konaté", poste: "Défenseur", club: "Liverpool" },
            { nom: "Jules Koundé", poste: "Défenseur", club: "FC Barcelone" },
            { nom: "Maxence Lacroix", poste: "Défenseur", club: "Paris SG" },
            { nom: "William Saliba", poste: "Défenseur", club: "Arsenal" },
            { nom: "Dayot Upamecano", poste: "Défenseur", club: "Bayern Munich" },
            { nom: "N'Golo Kanté", poste: "Milieu", club: "Al-Ittihad" },
            { nom: "Manu Koné", poste: "Milieu", club: "Real Madrid" },
            { nom: "Adrien Rabiot", poste: "Milieu", club: "Marseille" },
            { nom: "Aurélien Tchouaméni", poste: "Milieu", club: "Real Madrid" },
            { nom: "Warren Zaïre-Emery", poste: "Milieu", club: "Paris SG" },
            { nom: "Maghnes Akliouche", poste: "Attaquant", club: "Monaco" },
            { nom: "Bradley Barcola", poste: "Attaquant", club: "Paris SG" },
            { nom: "Rayan Cherki", poste: "Attaquant", club: "Paris SG" },
            { nom: "Ousmane Dembélé", poste: "Attaquant", club: "Paris SG" },
            { nom: "Désiré Doué", poste: "Attaquant", club: "Paris SG" },
            { nom: "Jean-Philippe Mateta", poste: "Attaquant", club: "Crystal Palace" },
            { nom: "Kylian Mbappé", poste: "Attaquant", club: "Real Madrid" },
            { nom: "Michael Olise", poste: "Attaquant", club: "Bayern Munich" },
            { nom: "Marcus Thuram", poste: "Attaquant", club: "Inter Milan" }
        ]
    },
    "Germany": {
        entraineur: "Julian Nagelsmann",
        titres: ["Champion du Monde 1954", "Champion du Monde 1974", "Champion du Monde 1990", "Champion du Monde 2014"],
        participations: [
            { annee: 1934, phase: "3e place" },
            { annee: 1938, phase: "1er tour" },
            { annee: 1954, phase: "Vainqueur" },
            { annee: 1958, phase: "4e place" },
            { annee: 1962, phase: "QF" },
            { annee: 1966, phase: "Finaliste" },
            { annee: 1970, phase: "3e place" },
            { annee: 1974, phase: "Vainqueur" },
            { annee: 1978, phase: "2e tour" },
            { annee: 1982, phase: "Finaliste" },
            { annee: 1986, phase: "Finaliste" },
            { annee: 1990, phase: "Vainqueur" },
            { annee: 1994, phase: "QF" },
            { annee: 1998, phase: "QF" },
            { annee: 2002, phase: "Finaliste" },
            { annee: 2006, phase: "3e place" },
            { annee: 2010, phase: "3e place" },
            { annee: 2014, phase: "Vainqueur" },
            { annee: 2018, phase: "1er tour" },
            { annee: 2022, phase: "1er tour" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Manuel Neuer", poste: "Gardien", club: "Bayern Munich" },
            { nom: "Marc-André ter Stegen", poste: "Gardien", club: "FC Barcelone" },
            { nom: "Alexander Nübel", poste: "Gardien", club: "Stuttgart" },
            { nom: "Toni Rüdiger", poste: "Défenseur", club: "Real Madrid" },
            { nom: "Joshua Kimmich", poste: "Défenseur", club: "Bayern Munich" },
            { nom: "Nico Schlotterbeck", poste: "Défenseur", club: "Borussia Dortmund" },
            { nom: "Jonathan Tah", poste: "Défenseur", club: "Bayer Leverkusen" },
            { nom: "Maximilian Mittelstädt", poste: "Défenseur", club: "Stuttgart" },
            { nom: "Florian Wirtz", poste: "Milieu", club: "Bayer Leverkusen" },
            { nom: "Jamal Musiala", poste: "Milieu", club: "Bayern Munich" },
            { nom: "Leon Goretzka", poste: "Milieu", club: "Bayern Munich" },
            { nom: "Robert Andrich", poste: "Milieu", club: "Bayer Leverkusen" },
            { nom: "Pascal Groß", poste: "Milieu", club: "Borussia Dortmund" },
            { nom: "Thomas Müller", poste: "Attaquant", club: "Bayern Munich" },
            { nom: "Kai Havertz", poste: "Attaquant", club: "Arsenal" },
            { nom: "Leroy Sané", poste: "Attaquant", club: "Bayern Munich" },
            { nom: "Niclas Füllkrug", poste: "Attaquant", club: "West Ham" },
            { nom: "Chris Führich", poste: "Attaquant", club: "Stuttgart" }
        ]
    },
    "Ghana": {
        entraineur: "Otto Addo",
        titres: [],
        participations: [
            { annee: 2006, phase: "R16" },
            { annee: 2010, phase: "QF" },
            { annee: 2014, phase: "1er tour" },
            { annee: 2022, phase: "1er tour" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Lawrence Ati-Zigi", poste: "Gardien", club: "St. Gallen" },
            { nom: "Abdul Manaf Nurudeen", poste: "Gardien", club: "Kasımpaşa" },
            { nom: "Tariq Lamptey", poste: "Défenseur", club: "Brighton" },
            { nom: "Alexander Djiku", poste: "Défenseur", club: "Fenerbahçe" },
            { nom: "Daniel Amartey", poste: "Défenseur", club: "Leicester City" },
            { nom: "Abdul Rahman Baba", poste: "Défenseur", club: "Reading" },
            { nom: "Gideon Mensah", poste: "Défenseur", club: "Auxerre" },
            { nom: "Thomas Partey", poste: "Milieu", club: "Arsenal" },
            { nom: "Iddrisu Baba", poste: "Milieu", club: "Majorque" },
            { nom: "Salis Abdul Samed", poste: "Milieu", club: "RC Lens" },
            { nom: "Mohammed Kudus", poste: "Milieu", club: "West Ham" },
            { nom: "Jordan Ayew", poste: "Attaquant", club: "Leicester City" },
            { nom: "Antoine Semenyo", poste: "Attaquant", club: "Bournemouth" },
            { nom: "Inaki Williams", poste: "Attaquant", club: "Athletic Club" },
            { nom: "Osman Bukari", poste: "Attaquant", club: "Red Star Belgrade" }
        ]
    },
    "Haiti": {
        entraineur: "Marc Collat",
        titres: [],
        participations: [
            { annee: 1974, phase: "1er tour" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Jhony Placide", poste: "Gardien", club: "Toulouse" },
            { nom: "Zachary Herivaux", poste: "Gardien", club: "FC Dallas" },
            { nom: "Mechack Jérôme", poste: "Défenseur", club: "Vancouver Whitecaps" },
            { nom: "Kervens Belfort", poste: "Défenseur", club: "Sportivo Luqueño" },
            { nom: "Wilde-Donald Guerrier", poste: "Défenseur", club: "Nîmes" },
            { nom: "Frantzdy Pierrot", poste: "Milieu", club: "Columbus Crew" },
            { nom: "Duckens Nazon", poste: "Milieu", club: "Saint-Trond" },
            { nom: "Steeven Saba", poste: "Milieu", club: "Le Havre" },
            { nom: "Carnejy Antoine", poste: "Milieu", club: "Columbus Crew" },
            { nom: "Derrick Étienne", poste: "Attaquant", club: "Columbus Crew" },
            { nom: "Nicolas Gérard", poste: "Attaquant", club: "New England Revolution" },
            { nom: "Gesner Jocelyn", poste: "Attaquant", club: "Guingamp" }
        ]
    },
    "Iran": {
        entraineur: "Amir Ghalenoei",
        titres: [],
        participations: [
            { annee: 1978, phase: "1er tour" },
            { annee: 1998, phase: "1er tour" },
            { annee: 2006, phase: "1er tour" },
            { annee: 2014, phase: "1er tour" },
            { annee: 2018, phase: "1er tour" },
            { annee: 2022, phase: "1er tour" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Alireza Beiranvand", poste: "Gardien", club: "Persepolis" },
            { nom: "Amir Abedzadeh", poste: "Gardien", club: "Maritimo" },
            { nom: "Sadegh Moharrami", poste: "Défenseur", club: "Dinamo Zagreb" },
            { nom: "Milad Mohammadi", poste: "Défenseur", club: "Akhmat Grozny" },
            { nom: "Majid Hosseini", poste: "Défenseur", club: "Kasımpaşa" },
            { nom: "Shoja Khalilzadeh", poste: "Défenseur", club: "Al-Duhail" },
            { nom: "Ehsan Hajsafi", poste: "Défenseur", club: "Panathinaikos" },
            { nom: "Saeid Ezatolahi", poste: "Milieu", club: "Cercle Bruges" },
            { nom: "Ahmad Noorollahi", poste: "Milieu", club: "Al-Sailiya" },
            { nom: "Ali Gholizadeh", poste: "Milieu", club: "Charleroi" },
            { nom: "Mehdi Taremi", poste: "Attaquant", club: "Inter Milan" },
            { nom: "Sardar Azmoun", poste: "Attaquant", club: "Bayer Leverkusen" },
            { nom: "Alireza Jahanbakhsh", poste: "Attaquant", club: "Feyenoord" },
            { nom: "Allahyar Sayyadmanesh", poste: "Attaquant", club: "Kasımpaşa" }
        ]
    },
    "Iraq": {
        entraineur: "Jesús Casas",
        titres: [],
        participations: [
            { annee: 1986, phase: "1er tour" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Jalal Hassan", poste: "Gardien", club: "Al-Zawraa" },
            { nom: "Dhurgham Ismail", poste: "Gardien", club: "Airbus UK" },
            { nom: "Ali Adnan", poste: "Défenseur", club: "FC Cincinnati" },
            { nom: "Rebin Sulaka", poste: "Défenseur", club: "IFK Göteborg" },
            { nom: "Saad Abdul Amir", poste: "Défenseur", club: "Al-Quwa Al-Jawiya" },
            { nom: "Ahmed Ibrahim", poste: "Défenseur", club: "Al-Shorta" },
            { nom: "Amjad Attwan", poste: "Milieu", club: "Al-Zawraa" },
            { nom: "Humam Tariq", poste: "Milieu", club: "Al-Quwa Al-Jawiya" },
            { nom: "Bashar Reisan", poste: "Milieu", club: "Zob Ahan" },
            { nom: "Ibrahim Bayesh", poste: "Milieu", club: "Al-Faisaly" },
            { nom: "Ayman Hussein", poste: "Attaquant", club: "Al-Shorta" },
            { nom: "Mohanad Ali", poste: "Attaquant", club: "Al-Zawraa" },
            { nom: "Alaa Abbas", poste: "Attaquant", club: "Al-Quwa Al-Jawiya" }
        ]
    },
    "Ivory Coast": {
        entraineur: "Emerse Faé",
        titres: [],
        participations: [
            { annee: 2006, phase: "1er tour" },
            { annee: 2010, phase: "1er tour" },
            { annee: 2014, phase: "1er tour" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Yahia Fofana", poste: "Gardien", club: "Leicester City" },
            { nom: "Badra Ali Sangaré", poste: "Gardien", club: "Wolfsberger" },
            { nom: "Serge Aurier", poste: "Défenseur", club: "Nottingham Forest" },
            { nom: "Simon Deli", poste: "Défenseur", club: "Club Brugge" },
            { nom: "Odilon Kossounou", poste: "Défenseur", club: "Bayer Leverkusen" },
            { nom: "Wilfried Singo", poste: "Défenseur", club: "Monaco" },
            { nom: "Ghislain Konan", poste: "Défenseur", club: "Reims" },
            { nom: "Jean Michaël Seri", poste: "Milieu", club: "Galatasaray" },
            { nom: "Ibrahim Sangaré", poste: "Milieu", club: "Nottingham Forest" },
            { nom: "Franck Kessié", poste: "Milieu", club: "FC Barcelone" },
            { nom: "Sébastien Haller", poste: "Attaquant", club: "Borussia Dortmund" },
            { nom: "Nicolas Pépé", poste: "Attaquant", club: "Nice" },
            { nom: "Wilfried Zaha", poste: "Attaquant", club: "Galatasaray" },
            { nom: "Jonathan Kodjia", poste: "Attaquant", club: "Al-Gharafa" },
            { nom: "Maxwel Cornet", poste: "Attaquant", club: "West Ham" }
        ]
    },
    "Japan": {
        entraineur: "Hajime Moriyasu",
        titres: [],
        participations: [
            { annee: 1998, phase: "1er tour" },
            { annee: 2002, phase: "R16" },
            { annee: 2006, phase: "1er tour" },
            { annee: 2010, phase: "R16" },
            { annee: 2014, phase: "1er tour" },
            { annee: 2018, phase: "R16" },
            { annee: 2022, phase: "R16" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Shuichi Gonda", poste: "Gardien", club: "Shimizu S-Pulse" },
            { nom: "Zion Suzuki", poste: "Gardien", club: "Cercle Bruges" },
            { nom: "Hiroki Sakai", poste: "Défenseur", club: "Urawa Red Diamonds" },
            { nom: "Ko Itakura", poste: "Défenseur", club: "Borussia Mönchengladbach" },
            { nom: "Maya Yoshida", poste: "Défenseur", club: "FC Barcelone" },
            { nom: "Yuto Nagatomo", poste: "Défenseur", club: "FC Tokyo" },
            { nom: "Takehiro Tomiyasu", poste: "Défenseur", club: "Arsenal" },
            { nom: "Wataru Endo", poste: "Milieu", club: "Liverpool" },
            { nom: "Hidemasa Morita", poste: "Milieu", club: "Sporting CP" },
            { nom: "Gaku Shibasaki", poste: "Milieu", club: "Deportivo" },
            { nom: "Daichi Kamada", poste: "Milieu", club: "Lazio" },
            { nom: "Takumi Minamino", poste: "Milieu", club: "Monaco" },
            { nom: "Kaoru Mitoma", poste: "Attaquant", club: "Brighton" },
            { nom: "Ritsu Doan", poste: "Attaquant", club: "Freiburg" },
            { nom: "Ayase Ueda", poste: "Attaquant", club: "Feyenoord" },
            { nom: "Junya Ito", poste: "Attaquant", club: "Reims" },
            { nom: "Ao Tanaka", poste: "Milieu", club: "Borussia Dortmund" }
        ]
    },
    "Jordan": {
        entraineur: "Hussein Ammouta",
        titres: [],
        participations: [
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Yazeed Abo Laila", poste: "Gardien", club: "Al-Faisaly" },
            { nom: "Amer Shafi", poste: "Gardien", club: "Al-Wehdat" },
            { nom: "Yazan Al-Naimat", poste: "Défenseur", club: "Al-Ramtha" },
            { nom: "Anas Bani Yaseen", poste: "Défenseur", club: "Al-Qadsia" },
            { nom: "Mahmoud Rashid", poste: "Défenseur", club: "Al-Faisaly" },
            { nom: "Ahmad Hamdallah", poste: "Milieu", club: "Al-Nassr" },
            { nom: "Mousa Al-Taamari", poste: "Milieu", club: "Montpellier" },
            { nom: "Baha' Faisal", poste: "Milieu", club: "Al-Wehdat" },
            { nom: "Musa Al-Tamari", poste: "Milieu", club: "Club Brugge" },
            { nom: "Hamza Al-Dardour", poste: "Attaquant", club: "Al-Qadsia" },
            { nom: "Zaid Al-Qasim", poste: "Attaquant", club: "Al-Faisaly" },
            { nom: "Baha Faisal", poste: "Attaquant", club: "Al-Ramtha" }
        ]
    },
    "Mexico": {
        entraineur: "Javier Aguirre",
        titres: [],
        participations: [
            { annee: 1930, phase: "1er tour" },
            { annee: 1950, phase: "1er tour" },
            { annee: 1954, phase: "1er tour" },
            { annee: 1958, phase: "1er tour" },
            { annee: 1962, phase: "1er tour" },
            { annee: 1966, phase: "1er tour" },
            { annee: 1970, phase: "QF" },
            { annee: 1978, phase: "1er tour" },
            { annee: 1986, phase: "QF" },
            { annee: 1994, phase: "R16" },
            { annee: 1998, phase: "R16" },
            { annee: 2002, phase: "R16" },
            { annee: 2006, phase: "R16" },
            { annee: 2010, phase: "R16" },
            { annee: 2014, phase: "R16" },
            { annee: 2018, phase: "R16" },
            { annee: 2022, phase: "1er tour" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Guillermo Ochoa", poste: "Gardien", club: "América" },
            { nom: "Rodolfo Cota", poste: "Gardien", club: "León" },
            { nom: "Jorge Sánchez", poste: "Défenseur", club: "Ajax" },
            { nom: "César Montes", poste: "Défenseur", club: "Espanyol" },
            { nom: "Gerardo Arteaga", poste: "Défenseur", club: "Getafe" },
            { nom: "Johan Vásquez", poste: "Défenseur", club: "Génova" },
            { nom: "Jesús Gallardo", poste: "Défenseur", club: "Monterrey" },
            { nom: "Edson Álvarez", poste: "Milieu", club: "West Ham" },
            { nom: "Carlos Rodríguez", poste: "Milieu", club: "Cruz Azul" },
            { nom: "Héctor Herrera", poste: "Milieu", club: "Houston Dynamo" },
            { nom: "Uriel Antuna", poste: "Milieu", club: "Cruz Azul" },
            { nom: "Hirving Lozano", poste: "Attaquant", club: "PSV Eindhoven" },
            { nom: "Henry Martín", poste: "Attaquant", club: "América" },
            { nom: "Raúl Jiménez", poste: "Attaquant", club: "Fulham" },
            { nom: "Santiago Giménez", poste: "Attaquant", club: "Feyenoord" },
            { nom: "Alexis Vega", poste: "Attaquant", club: "Guadalajara" }
        ]
    },
    "Morocco": {
        entraineur: "Walid Regragui",
        titres: [],
        participations: [
            { annee: 1970, phase: "1er tour" },
            { annee: 1986, phase: "R16" },
            { annee: 1994, phase: "1er tour" },
            { annee: 1998, phase: "1er tour" },
            { annee: 2018, phase: "1er tour" },
            { annee: 2022, phase: "4e place" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Yassine Bounou", poste: "Gardien", club: "Al-Hilal" },
            { nom: "Munir Mohamedi", poste: "Gardien", club: "RC Lens" },
            { nom: "Achraf Hakimi", poste: "Défenseur", club: "Paris SG" },
            { nom: "Noussair Mazraoui", poste: "Défenseur", club: "Manchester United" },
            { nom: "Romain Saïss", poste: "Défenseur", club: "Beşiktaş" },
            { nom: "Nayef Aguerd", poste: "Défenseur", club: "West Ham" },
            { nom: "Yahia Attiyat Allah", poste: "Défenseur", club: "Wydad AC" },
            { nom: "Azzedine Ounahi", poste: "Milieu", club: "Marseille" },
            { nom: "Sofyan Amrabat", poste: "Milieu", club: "Fiorentina" },
            { nom: "Bilal El Khannous", poste: "Milieu", club: "Genk" },
            { nom: "Hakim Ziyech", poste: "Attaquant", club: "Galatasaray" },
            { nom: "Youssef En-Nesyri", poste: "Attaquant", club: "Fenerbahçe" },
            { nom: "Sofiane Boufal", poste: "Attaquant", club: "Al-Qadsiah" },
            { nom: "Abde Ezzalzouli", poste: "Attaquant", club: "Betis" },
            { nom: "Zakaria Aboukhlal", poste: "Attaquant", club: "Toulouse" }
        ]
    },
    "Netherlands": {
        entraineur: "Ronald Koeman",
        titres: [],
        participations: [
            { annee: 1934, phase: "1er tour" },
            { annee: 1938, phase: "1er tour" },
            { annee: 1974, phase: "Finaliste" },
            { annee: 1978, phase: "Finaliste" },
            { annee: 1990, phase: "R16" },
            { annee: 1994, phase: "QF" },
            { annee: 1998, phase: "4e place" },
            { annee: 2006, phase: "R16" },
            { annee: 2010, phase: "Finaliste" },
            { annee: 2014, phase: "3e place" },
            { annee: 2022, phase: "QF" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Bart Verbruggen", poste: "Gardien", club: "Brighton" },
            { nom: "Mark Flekken", poste: "Gardien", club: "Brentford" },
            { nom: "Denzel Dumfries", poste: "Défenseur", club: "Inter Milan" },
            { nom: "Virgil van Dijk", poste: "Défenseur", club: "Liverpool" },
            { nom: "Stefan de Vrij", poste: "Défenseur", club: "Inter Milan" },
            { nom: "Nathan Aké", poste: "Défenseur", club: "Manchester City" },
            { nom: "Daley Blind", poste: "Défenseur", club: "Girona" },
            { nom: "Frenkie de Jong", poste: "Milieu", club: "FC Barcelone" },
            { nom: "Tijjani Reijnders", poste: "Milieu", club: "AC Milan" },
            { nom: "Teun Koopmeiners", poste: "Milieu", club: "Juventus" },
            { nom: "Jerdy Schouten", poste: "Milieu", club: "Bologna" },
            { nom: "Cody Gakpo", poste: "Attaquant", club: "Liverpool" },
            { nom: "Donyell Malen", poste: "Attaquant", club: "Aston Villa" },
            { nom: "Steven Bergwijn", poste: "Attaquant", club: "Ajax" },
            { nom: "Memphis Depay", poste: "Attaquant", club: "Atletico Madrid" },
            { nom: "Wout Weghorst", poste: "Attaquant", club: "Hoffenheim" }
        ]
    },
    "New Zealand": {
        entraineur: "Darren Bazeley",
        titres: [],
        participations: [
            { annee: 1982, phase: "1er tour" },
            { annee: 2010, phase: "1er tour" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Oliver Sail", poste: "Gardien", club: "Wellington Phoenix" },
            { nom: "Stefan Marinovic", poste: "Gardien", club: "Vancouver Whitecaps" },
            { nom: "Bill Tuiloma", poste: "Défenseur", club: "Portland Timbers" },
            { nom: "Tommy Smith", poste: "Défenseur", club: "Colorado Rapids" },
            { nom: "Tim Payne", poste: "Défenseur", club: "Wellington Phoenix" },
            { nom: "Clayton Lewis", poste: "Milieu", club: "Macarthur FC" },
            { nom: "Liberato Cacace", poste: "Milieu", club: "Empoli" },
            { nom: "Joe Bell", poste: "Milieu", club: "SV Darmstadt 98" },
            { nom: "Elijah Just", poste: "Milieu", club: "Colorado Rapids" },
            { nom: "Sarpreet Singh", poste: "Attaquant", club: "Jahn Regensburg" },
            { nom: "Chris Wood", poste: "Attaquant", club: "Nottingham Forest" },
            { nom: "Kosta Barbarouses", poste: "Attaquant", club: "Vancouver Whitecaps" }
        ]
    },
    "Norway": {
        entraineur: "Ståle Solbakken",
        titres: [],
        participations: [
            { annee: 1938, phase: "1er tour" },
            { annee: 1994, phase: "1er tour" },
            { annee: 1998, phase: "1er tour" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Ørjan Nyland", poste: "Gardien", club: "Southampton" },
            { nom: "Håkon Opdal", poste: "Gardien", club: "Stabæk" },
            { nom: "Kristoffer Ajer", poste: "Défenseur", club: "Brentford" },
            { nom: "Leo Skiri Østigård", poste: "Défenseur", club: "Napoli" },
            { nom: "Andreas Hanche-Olsen", poste: "Défenseur", club: "KAA Gent" },
            { nom: "Fredrik Bjørkan", poste: "Défenseur", club: "Heerenveen" },
            { nom: "Sander Berge", poste: "Milieu", club: "Fulham" },
            { nom: "Martin Ødegaard", poste: "Milieu", club: "Arsenal" },
            { nom: "Morten Thorsby", poste: "Milieu", club: "Genoa" },
            { nom: "Fredrik Aursnes", poste: "Milieu", club: "Benfica" },
            { nom: "Erling Haaland", poste: "Attaquant", club: "Manchester City" },
            { nom: "Alexander Sørloth", poste: "Attaquant", club: "Atletico Madrid" },
            { nom: "Mohamed Elyounoussi", poste: "Attaquant", club: "Celtic" },
            { nom: "Antonio Nusa", poste: "Attaquant", club: "Club Brugge" }
        ]
    },
    "Panama": {
        entraineur: "Thomas Christiansen",
        titres: [],
        participations: [
            { annee: 2018, phase: "1er tour" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Luis Mejía", poste: "Gardien", club: "Olimpia" },
            { nom: "Jaime Penedo", poste: "Gardien", club: "Independiente" },
            { nom: "Michael Murillo", poste: "Défenseur", club: "Anderlecht" },
            { nom: "Eric Davis", poste: "Défenseur", club: "Nashville SC" },
            { nom: "Fidel Escobar", poste: "Défenseur", club: "New York Red Bulls" },
            { nom: "Roderick Miller", poste: "Défenseur", club: "Club Deportivo Árabe Unido" },
            { nom: "Anibal Godoy", poste: "Milieu", club: "Nashville SC" },
            { nom: "Alberto Quintero", poste: "Milieu", club: "Universitario" },
            { nom: "Adalberto Carrasquilla", poste: "Milieu", club: "D.C. United" },
            { nom: "José Fajardo", poste: "Attaquant", club: "FC Dallas" },
            { nom: "Ismael Díaz", poste: "Attaquant", club: "Mainz" },
            { nom: "Rolando Blackburn", poste: "Attaquant", club: "Nashville SC" }
        ]
    },
    "Paraguay": {
        entraineur: "Gustavo Alfaro",
        titres: [],
        participations: [
            { annee: 1930, phase: "1er tour" },
            { annee: 1950, phase: "1er tour" },
            { annee: 1958, phase: "1er tour" },
            { annee: 1986, phase: "R16" },
            { annee: 1998, phase: "R16" },
            { annee: 2002, phase: "1er tour" },
            { annee: 2006, phase: "R16" },
            { annee: 2010, phase: "QF" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Antony Silva", poste: "Gardien", club: "Club Olimpia" },
            { nom: "Alfredo Aguilar", poste: "Gardien", club: "Cerro Porteño" },
            { nom: "Junior Alonso", poste: "Défenseur", club: "Atlético Mineiro" },
            { nom: "Gustavo Gómez", poste: "Défenseur", club: "Palmeiras" },
            { nom: "Omar Alderete", poste: "Défenseur", club: "Hertha Berlin" },
            { nom: "Fabián Balbuena", poste: "Défenseur", club: "West Ham" },
            { nom: "Santiago Arzamendia", poste: "Défenseur", club: "Cadix" },
            { nom: "Mathías Villasanti", poste: "Milieu", club: "Grêmio" },
            { nom: "Andrés Cubas", poste: "Milieu", club: "Nice" },
            { nom: "Ángel Romero", poste: "Milieu", club: "Corinthians" },
            { nom: "Miguel Almirón", poste: "Milieu", club: "Newcastle" },
            { nom: "Antonio Sanabria", poste: "Attaquant", club: "Torino" },
            { nom: "Carlos González", poste: "Attaquant", club: "Tigres UANL" },
            { nom: "Enciso Julio", poste: "Attaquant", club: "Brighton" }
        ]
    },
    "Portugal": {
        entraineur: "Roberto Martínez",
        titres: [],
        participations: [
            { annee: 1966, phase: "3e place" },
            { annee: 1986, phase: "1er tour" },
            { annee: 2002, phase: "1er tour" },
            { annee: 2006, phase: "4e place" },
            { annee: 2010, phase: "R16" },
            { annee: 2014, phase: "1er tour" },
            { annee: 2018, phase: "R16" },
            { annee: 2022, phase: "QF" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Diogo Costa", poste: "Gardien", club: "FC Porto" },
            { nom: "Rui Patrício", poste: "Gardien", club: "Roma" },
            { nom: "Diogo Dalot", poste: "Défenseur", club: "Manchester United" },
            { nom: "Rúben Dias", poste: "Défenseur", club: "Manchester City" },
            { nom: "Pepe", poste: "Défenseur", club: "FC Porto" },
            { nom: "Nuno Mendes", poste: "Défenseur", club: "Paris SG" },
            { nom: "João Cancelo", poste: "Défenseur", club: "FC Barcelone" },
            { nom: "Rúben Neves", poste: "Milieu", club: "Al-Hilal" },
            { nom: "Vitinha", poste: "Milieu", club: "Paris SG" },
            { nom: "João Palhinha", poste: "Milieu", club: "Bayern Munich" },
            { nom: "Bruno Fernandes", poste: "Milieu", club: "Manchester United" },
            { nom: "Bernardo Silva", poste: "Milieu", club: "Manchester City" },
            { nom: "Cristiano Ronaldo", poste: "Attaquant", club: "Al-Nassr" },
            { nom: "Rafael Leão", poste: "Attaquant", club: "AC Milan" },
            { nom: "Gonçalo Ramos", poste: "Attaquant", club: "Paris SG" },
            { nom: "Pedro Neto", poste: "Attaquant", club: "Chelsea" },
            { nom: "João Félix", poste: "Attaquant", club: "FC Barcelone" }
        ]
    },
    "Qatar": {
        entraineur: "Marquez Lopez",
        titres: [],
        participations: [
            { annee: 2022, phase: "1er tour" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Meshaal Barsham", poste: "Gardien", club: "Al-Sadd" },
            { nom: "Saad Al Sheeb", poste: "Gardien", club: "Al-Sadd" },
            { nom: "Pedro Miguel", poste: "Défenseur", club: "Al-Sadd" },
            { nom: "Boualem Khoukhi", poste: "Défenseur", club: "Al-Sadd" },
            { nom: "Tarek Salman", poste: "Défenseur", club: "Al-Duhail" },
            { nom: "Karim Boudiaf", poste: "Milieu", club: "Al-Duhail" },
            { nom: "Abdulaziz Hatem", poste: "Milieu", club: "Al-Rayyan" },
            { nom: "Assim Madibo", poste: "Milieu", club: "Al-Duhail" },
            { nom: "Hassan Al-Haydos", poste: "Milieu", club: "Al-Sadd" },
            { nom: "Akram Afif", poste: "Attaquant", club: "Al-Sadd" },
            { nom: "Almoez Ali", poste: "Attaquant", club: "Al-Duhail" },
            { nom: "Mohammed Muntari", poste: "Attaquant", club: "Al-Duhail" }
        ]
    },
    "Saudi Arabia": {
        entraineur: "Hervé Renard",
        titres: [],
        participations: [
            { annee: 1994, phase: "R16" },
            { annee: 1998, phase: "1er tour" },
            { annee: 2002, phase: "1er tour" },
            { annee: 2006, phase: "1er tour" },
            { annee: 2018, phase: "1er tour" },
            { annee: 2022, phase: "R16" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Mohammed Al-Owais", poste: "Gardien", club: "Al-Hilal" },
            { nom: "Fawaz Al-Qarni", poste: "Gardien", club: "Al-Ittihad" },
            { nom: "Saud Abdulhamid", poste: "Défenseur", club: "Al-Hilal" },
            { nom: "Ali Al-Bulaihi", poste: "Défenseur", club: "Al-Hilal" },
            { nom: "Abdulelah Al-Amri", poste: "Défenseur", club: "Al-Hilal" },
            { nom: "Yasser Al-Shahrani", poste: "Défenseur", club: "Al-Hilal" },
            { nom: "Riyadh Sharahili", poste: "Défenseur", club: "Al-Ittihad" },
            { nom: "Salman Al-Faraj", poste: "Milieu", club: "Al-Hilal" },
            { nom: "Mohamed Kanno", poste: "Milieu", club: "Al-Hilal" },
            { nom: "Hattan Bahebri", poste: "Milieu", club: "Al-Shabab" },
            { nom: "Sami Al-Najei", poste: "Milieu", club: "Al-Ittihad" },
            { nom: "Salem Al-Dawsari", poste: "Attaquant", club: "Al-Hilal" },
            { nom: "Firas Al-Buraikan", poste: "Attaquant", club: "Al-Fateh" },
            { nom: "Abdullah Al-Hamdan", poste: "Attaquant", club: "Al-Shabab" },
            { nom: "Marwan Al-Sahafi", poste: "Attaquant", club: "Damac FC" }
        ]
    },
    "Scotland": {
        entraineur: "Steve Clarke",
        titres: [],
        participations: [
            { annee: 1954, phase: "1er tour" },
            { annee: 1958, phase: "1er tour" },
            { annee: 1974, phase: "1er tour" },
            { annee: 1978, phase: "1er tour" },
            { annee: 1982, phase: "1er tour" },
            { annee: 1986, phase: "1er tour" },
            { annee: 1990, phase: "1er tour" },
            { annee: 1998, phase: "1er tour" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Angus Gunn", poste: "Gardien", club: "Norwich City" },
            { nom: "Craig Gordon", poste: "Gardien", club: "Hearts" },
            { nom: "Aaron Hickey", poste: "Défenseur", club: "Brentford" },
            { nom: "Andrew Robertson", poste: "Défenseur", club: "Liverpool" },
            { nom: "Grant Hanley", poste: "Défenseur", club: "Norwich City" },
            { nom: "Scott McKenna", poste: "Défenseur", club: "Nottingham Forest" },
            { nom: "Jack Hendry", poste: "Défenseur", club: "Club Brugge" },
            { nom: "Billy Gilmour", poste: "Milieu", club: "Brighton" },
            { nom: "John McGinn", poste: "Milieu", club: "Aston Villa" },
            { nom: "Stuart Armstrong", poste: "Milieu", club: "Southampton" },
            { nom: "Callum McGregor", poste: "Milieu", club: "Celtic" },
            { nom: "Ryan Christie", poste: "Milieu", club: "Bournemouth" },
            { nom: "Ryan Fraser", poste: "Attaquant", club: "Southampton" },
            { nom: "Lyndon Dykes", poste: "Attaquant", club: "QPR" },
            { nom: "Che Adams", poste: "Attaquant", club: "Southampton" },
            { nom: "Kieran Tierney", poste: "Défenseur", club: "Real Sociedad" }
        ]
    },
    "Senegal": {
        entraineur: "Aliou Cissé",
        titres: [],
        participations: [
            { annee: 2002, phase: "QF" },
            { annee: 2018, phase: "1er tour" },
            { annee: 2022, phase: "R16" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Edouard Mendy", poste: "Gardien", club: "Chelsea" },
            { nom: "Alfred Gomis", poste: "Gardien", club: "Rennes" },
            { nom: "Youssouf Sabaly", poste: "Défenseur", club: "Betis" },
            { nom: "Kalidou Koulibaly", poste: "Défenseur", club: "Al-Hilal" },
            { nom: "Abdou Diallo", poste: "Défenseur", club: "RB Leipzig" },
            { nom: "Fodé Ballo-Touré", poste: "Défenseur", club: "AC Milan" },
            { nom: "Pape Abou Cissé", poste: "Défenseur", club: "Olympiakos" },
            { nom: "Idrissa Gueye", poste: "Milieu", club: "Everton" },
            { nom: "Nampalys Mendy", poste: "Milieu", club: "Leicester City" },
            { nom: "Pape Matar Sarr", poste: "Milieu", club: "Tottenham" },
            { nom: "Krepin Diatta", poste: "Milieu", club: "Monaco" },
            { nom: "Sadio Mané", poste: "Attaquant", club: "Al-Nassr" },
            { nom: "Ismaïla Sarr", poste: "Attaquant", club: "Crystal Palace" },
            { nom: "Habib Diallo", poste: "Attaquant", club: "Strasbourg" },
            { nom: "Nicolas Jackson", poste: "Attaquant", club: "Chelsea" }
        ]
    },
    "South Africa": {
        entraineur: "Hugo Broos",
        titres: [],
        participations: [
            { annee: 1998, phase: "1er tour" },
            { annee: 2002, phase: "1er tour" },
            { annee: 2010, phase: "1er tour" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Ronwen Williams", poste: "Gardien", club: "Mamelodi Sundowns" },
            { nom: "Veli Mothwa", poste: "Gardien", club: "AmaZulu" },
            { nom: "Sifiso Hlanti", poste: "Défenseur", club: "Kaizer Chiefs" },
            { nom: "Rushine De Reuck", poste: "Défenseur", club: "Mamelodi Sundowns" },
            { nom: "Thibang Phete", poste: "Défenseur", club: "Mamelodi Sundowns" },
            { nom: "Nyiko Mobbie", poste: "Défenseur", club: "Orlando Pirates" },
            { nom: "Evidence Makgopa", poste: "Attaquant", club: "Orlando Pirates" },
            { nom: "Percy Tau", poste: "Attaquant", club: "Al-Ahly" },
            { nom: "Lyle Foster", poste: "Attaquant", club: "Burnley" },
            { nom: "Themba Zwane", poste: "Milieu", club: "Mamelodi Sundowns" },
            { nom: "Bongani Zungu", poste: "Milieu", club: "Rangers" },
            { nom: "Teboho Mokoena", poste: "Milieu", club: "Mamelodi Sundowns" },
            { nom: "Keagan Dolly", poste: "Milieu", club: "Kaizer Chiefs" }
        ]
    },
    "South Korea": {
        entraineur: "Hong Myung-bo",
        titres: [],
        participations: [
            { annee: 1954, phase: "1er tour" },
            { annee: 1986, phase: "1er tour" },
            { annee: 1990, phase: "1er tour" },
            { annee: 1994, phase: "1er tour" },
            { annee: 1998, phase: "1er tour" },
            { annee: 2002, phase: "4e place" },
            { annee: 2006, phase: "1er tour" },
            { annee: 2010, phase: "R16" },
            { annee: 2014, phase: "1er tour" },
            { annee: 2018, phase: "1er tour" },
            { annee: 2022, phase: "R16" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Kim Seung-gyu", poste: "Gardien", club: "Vissel Kobe" },
            { nom: "Jo Hyeon-woo", poste: "Gardien", club: "Ulsan HD" },
            { nom: "Kim Moon-hwan", poste: "Défenseur", club: "Jeonbuk Motors" },
            { nom: "Kim Min-jae", poste: "Défenseur", club: "Bayern Munich" },
            { nom: "Jung Seung-hyun", poste: "Défenseur", club: "Al-Shabab" },
            { nom: "Hong Chul", poste: "Défenseur", club: "Suwon Samsung" },
            { nom: "Kim Jin-su", poste: "Défenseur", club: "Jeonbuk Motors" },
            { nom: "Jung Woo-young", poste: "Milieu", club: "Al-Qadsiah" },
            { nom: "Hwang In-beom", poste: "Milieu", club: "Feyenoord" },
            { nom: "Lee Kang-in", poste: "Milieu", club: "Paris SG" },
            { nom: "Paik Seung-ho", poste: "Milieu", club: "Jeonbuk Motors" },
            { nom: "Son Heung-min", poste: "Attaquant", club: "Tottenham" },
            { nom: "Hwang Hee-chan", poste: "Attaquant", club: "Wolverhampton" },
            { nom: "Cho Gue-sung", poste: "Attaquant", club: "Freiburg" },
            { nom: "Oh Hyeon-gyu", poste: "Attaquant", club: "Celtic" }
        ]
    },
    "Spain": {
        entraineur: "Luis de la Fuente",
        titres: ["Champion du Monde 2010"],
        participations: [
            { annee: 1934, phase: "QF" },
            { annee: 1950, phase: "4e place" },
            { annee: 1962, phase: "1er tour" },
            { annee: 1966, phase: "1er tour" },
            { annee: 1978, phase: "1er tour" },
            { annee: 1982, phase: "2e tour" },
            { annee: 1986, phase: "QF" },
            { annee: 1990, phase: "R16" },
            { annee: 1994, phase: "QF" },
            { annee: 1998, phase: "R16" },
            { annee: 2002, phase: "QF" },
            { annee: 2006, phase: "R16" },
            { annee: 2010, phase: "Vainqueur" },
            { annee: 2014, phase: "1er tour" },
            { annee: 2018, phase: "R16" },
            { annee: 2022, phase: "QF" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "David Raya", poste: "Gardien", club: "Arsenal" },
            { nom: "Unai Simón", poste: "Gardien", club: "Athletic Club" },
            { nom: "Dani Vivian", poste: "Défenseur", club: "Athletic Club" },
            { nom: "Daniel Carvajal", poste: "Défenseur", club: "Real Madrid" },
            { nom: "Aymeric Laporte", poste: "Défenseur", club: "Al-Nassr" },
            { nom: "Pau Cubarsí", poste: "Défenseur", club: "FC Barcelone" },
            { nom: "Alejandro Grimaldo", poste: "Défenseur", club: "Bayer Leverkusen" },
            { nom: "Marc Cucurella", poste: "Défenseur", club: "Chelsea" },
            { nom: "Rodri", poste: "Milieu", club: "Manchester City" },
            { nom: "Pedri", poste: "Milieu", club: "FC Barcelone" },
            { nom: "Fabian Ruiz", poste: "Milieu", club: "Paris SG" },
            { nom: "Martin Zubimendi", poste: "Milieu", club: "Arsenal" },
            { nom: "Dani Olmo", poste: "Milieu", club: "FC Barcelone" },
            { nom: "Fermín López", poste: "Milieu", club: "FC Barcelone" },
            { nom: "Álvaro Morata", poste: "Attaquant", club: "AC Milan" },
            { nom: "Mikel Oyarzabal", poste: "Attaquant", club: "Real Sociedad" },
            { nom: "Nico Williams", poste: "Attaquant", club: "Athletic Club" },
            { nom: "Lamine Yamal", poste: "Attaquant", club: "FC Barcelone" },
            { nom: "Ayoze Pérez", poste: "Attaquant", club: "Villarreal" }
        ]
    },
    "Sweden": {
        entraineur: "Jon Dahl Tomasson",
        titres: [],
        participations: [
            { annee: 1934, phase: "QF" },
            { annee: 1938, phase: "4e place" },
            { annee: 1950, phase: "Finaliste" },
            { annee: 1958, phase: "Finaliste" },
            { annee: 1970, phase: "1er tour" },
            { annee: 1974, phase: "2e tour" },
            { annee: 1978, phase: "1er tour" },
            { annee: 1990, phase: "R16" },
            { annee: 1994, phase: "3e place" },
            { annee: 2002, phase: "R16" },
            { annee: 2006, phase: "R16" },
            { annee: 2018, phase: "QF" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Robin Olsen", poste: "Gardien", club: "Aston Villa" },
            { nom: "Karl-Johan Johnsson", poste: "Gardien", club: "Guingamp" },
            { nom: "Emil Krafth", poste: "Défenseur", club: "Newcastle" },
            { nom: "Victor Lindelöf", poste: "Défenseur", club: "Manchester United" },
            { nom: "Isak Hien", poste: "Défenseur", club: "Atalanta" },
            { nom: "Ludwig Augustinsson", poste: "Défenseur", club: "Séville" },
            { nom: "Mikael Lustig", poste: "Défenseur", club: "AIK" },
            { nom: "Albin Ekdal", poste: "Milieu", club: "Sampdoria" },
            { nom: "Mattias Svanberg", poste: "Milieu", club: "Wolfsburg" },
            { nom: "Dejan Kulusevski", poste: "Milieu", club: "Tottenham" },
            { nom: "Emil Forsberg", poste: "Milieu", club: "RB Leipzig" },
            { nom: "Zlatan Ibrahimovic", poste: "Attaquant", club: "AC Milan" },
            { nom: "Alexander Isak", poste: "Attaquant", club: "Newcastle" },
            { nom: "Anthony Elanga", poste: "Attaquant", club: "Nottingham Forest" },
            { nom: "Viktor Gyökeres", poste: "Attaquant", club: "Sporting CP" }
        ]
    },
    "Switzerland": {
        entraineur: "Murat Yakin",
        titres: [],
        participations: [
            { annee: 1934, phase: "QF" },
            { annee: 1938, phase: "QF" },
            { annee: 1950, phase: "1er tour" },
            { annee: 1954, phase: "QF" },
            { annee: 1962, phase: "1er tour" },
            { annee: 1966, phase: "1er tour" },
            { annee: 1994, phase: "R16" },
            { annee: 2006, phase: "R16" },
            { annee: 2010, phase: "1er tour" },
            { annee: 2014, phase: "R16" },
            { annee: 2018, phase: "R16" },
            { annee: 2022, phase: "QF" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Yann Sommer", poste: "Gardien", club: "Inter Milan" },
            { nom: "Gregor Kobel", poste: "Gardien", club: "Borussia Dortmund" },
            { nom: "Silvan Widmer", poste: "Défenseur", club: "Mainz" },
            { nom: "Manuel Akanji", poste: "Défenseur", club: "Manchester City" },
            { nom: "Fabian Schär", poste: "Défenseur", club: "Newcastle" },
            { nom: "Ricardo Rodriguez", poste: "Défenseur", club: "Torino" },
            { nom: "Nico Elvedi", poste: "Défenseur", club: "Borussia Mönchengladbach" },
            { nom: "Granit Xhaka", poste: "Milieu", club: "Bayer Leverkusen" },
            { nom: "Remo Freuler", poste: "Milieu", club: "Bologna" },
            { nom: "Denis Zakaria", poste: "Milieu", club: "Chelsea" },
            { nom: "Djibril Sow", poste: "Milieu", club: "Eintracht Frankfurt" },
            { nom: "Ruben Vargas", poste: "Attaquant", club: "Augsburg" },
            { nom: "Haris Seferovic", poste: "Attaquant", club: "Galatasaray" },
            { nom: "Breel Embolo", poste: "Attaquant", club: "Monaco" },
            { nom: "Noah Okafor", poste: "Attaquant", club: "AC Milan" },
            { nom: "Dan Ndoye", poste: "Attaquant", club: "Bologna" }
        ]
    },
    "Tunisia": {
        entraineur: "Jalel Kadri",
        titres: [],
        participations: [
            { annee: 1978, phase: "1er tour" },
            { annee: 1998, phase: "1er tour" },
            { annee: 2002, phase: "1er tour" },
            { annee: 2006, phase: "1er tour" },
            { annee: 2018, phase: "1er tour" },
            { annee: 2022, phase: "1er tour" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Aymen Dahmen", poste: "Gardien", club: "Espérance Sportive" },
            { nom: "Bechir Ben Said", poste: "Gardien", club: "Club Africain" },
            { nom: "Mohamed Draeger", poste: "Défenseur", club: "Nantes" },
            { nom: "Montassar Talbi", poste: "Défenseur", club: "Lorient" },
            { nom: "Dylan Bronn", poste: "Défenseur", club: "Salernitana" },
            { nom: "Ali Maaloul", poste: "Défenseur", club: "Al-Ahly" },
            { nom: "Ellyes Skhiri", poste: "Milieu", club: "Eintracht Frankfurt" },
            { nom: "Anis Slimane", poste: "Milieu", club: "Brøndby" },
            { nom: "Wahbi Khazri", poste: "Milieu", club: "Montpellier" },
            { nom: "Hannibal Mejbri", poste: "Milieu", club: "Manchester United" },
            { nom: "Youssef Msakni", poste: "Attaquant", club: "Al-Duhail" },
            { nom: "Seifeddine Jaziri", poste: "Attaquant", club: "Montpellier" },
            { nom: "Naïm Sliti", poste: "Attaquant", club: "Dijon" },
            { nom: "Mohamed Ali Ben Romdhane", poste: "Attaquant", club: "Nantes" }
        ]
    },
    "Turkey": {
        entraineur: "Vincenzo Montella",
        titres: [],
        participations: [
            { annee: 1954, phase: "1er tour" },
            { annee: 2002, phase: "3e place" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Mert Günok", poste: "Gardien", club: "Beşiktaş" },
            { nom: "Altay Bayındır", poste: "Gardien", club: "Manchester United" },
            { nom: "Zeki Çelik", poste: "Défenseur", club: "Roma" },
            { nom: "Merih Demiral", poste: "Défenseur", club: "Al-Qadsiah" },
            { nom: "Samet Akaydın", poste: "Défenseur", club: "Séville" },
            { nom: "Ferdi Kadıoğlu", poste: "Défenseur", club: "Brighton" },
            { nom: "Abdülkerim Bardakcı", poste: "Défenseur", club: "Galatasaray" },
            { nom: "Hakan Çalhanoğlu", poste: "Milieu", club: "Inter Milan" },
            { nom: "Salih Özcan", poste: "Milieu", club: "Borussia Dortmund" },
            { nom: "İsmail Yüksek", poste: "Milieu", club: "Fenerbahçe" },
            { nom: "Kerem Aktürkoğlu", poste: "Milieu", club: "Galatasaray" },
            { nom: "Arda Güler", poste: "Attaquant", club: "Real Madrid" },
            { nom: "Burak Yılmaz", poste: "Attaquant", club: "Adana Demirspor" },
            { nom: "Baris Alper Yilmaz", poste: "Attaquant", club: "Galatasaray" },
            { nom: "Cenk Tosun", poste: "Attaquant", club: "Beşiktaş" }
        ]
    },
    "United States": {
        entraineur: "Mauricio Pochettino",
        titres: [],
        participations: [
            { annee: 1930, phase: "3e place" },
            { annee: 1934, phase: "1er tour" },
            { annee: 1950, phase: "1er tour" },
            { annee: 1990, phase: "1er tour" },
            { annee: 1994, phase: "R16" },
            { annee: 1998, phase: "1er tour" },
            { annee: 2002, phase: "QF" },
            { annee: 2006, phase: "1er tour" },
            { annee: 2010, phase: "R16" },
            { annee: 2014, phase: "R16" },
            { annee: 2022, phase: "R16" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Matt Turner", poste: "Gardien", club: "Crystal Palace" },
            { nom: "Patrick Schulte", poste: "Gardien", club: "Columbus Crew" },
            { nom: "Sergino Dest", poste: "Défenseur", club: "PSV Eindhoven" },
            { nom: "Joe Scally", poste: "Défenseur", club: "Borussia Mönchengladbach" },
            { nom: "Tim Ream", poste: "Défenseur", club: "Charlotte FC" },
            { nom: "Chris Richards", poste: "Défenseur", club: "Crystal Palace" },
            { nom: "Antonee Robinson", poste: "Défenseur", club: "Fulham" },
            { nom: "Yunus Musah", poste: "Milieu", club: "AC Milan" },
            { nom: "Tyler Adams", poste: "Milieu", club: "Bournemouth" },
            { nom: "Weston McKennie", poste: "Milieu", club: "Juventus" },
            { nom: "Gio Reyna", poste: "Milieu", club: "Borussia Dortmund" },
            { nom: "Christian Pulisic", poste: "Attaquant", club: "AC Milan" },
            { nom: "Josh Sargent", poste: "Attaquant", club: "Norwich City" },
            { nom: "Ricardo Pepi", poste: "Attaquant", club: "PSV Eindhoven" },
            { nom: "Tim Weah", poste: "Attaquant", club: "Juventus" },
            { nom: "Folarin Balogun", poste: "Attaquant", club: "Monaco" }
        ]
    },
    "Uruguay": {
        entraineur: "Marcelo Bielsa",
        titres: ["Champion du Monde 1930", "Champion du Monde 1950"],
        participations: [
            { annee: 1930, phase: "Vainqueur" },
            { annee: 1950, phase: "Vainqueur" },
            { annee: 1954, phase: "4e place" },
            { annee: 1962, phase: "1er tour" },
            { annee: 1966, phase: "QF" },
            { annee: 1970, phase: "4e place" },
            { annee: 1974, phase: "1er tour" },
            { annee: 1986, phase: "R16" },
            { annee: 1990, phase: "R16" },
            { annee: 2002, phase: "1er tour" },
            { annee: 2010, phase: "4e place" },
            { annee: 2014, phase: "R16" },
            { annee: 2018, phase: "QF" },
            { annee: 2022, phase: "1er tour" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Sergio Rochet", poste: "Gardien", club: "Nacional" },
            { nom: "Fernando Muslera", poste: "Gardien", club: "Galatasaray" },
            { nom: "Nahitan Nández", poste: "Défenseur", club: "Cagliari" },
            { nom: "José María Giménez", poste: "Défenseur", club: "Atletico Madrid" },
            { nom: "Diego Godín", poste: "Défenseur", club: "Vélez Sarsfield" },
            { nom: "Martín Cáceres", poste: "Défenseur", club: "Nacional" },
            { nom: "Mathías Olivera", poste: "Défenseur", club: "Napoli" },
            { nom: "Federico Valverde", poste: "Milieu", club: "Real Madrid" },
            { nom: "Rodrigo Bentancur", poste: "Milieu", club: "Tottenham" },
            { nom: "Lucas Torreira", poste: "Milieu", club: "Galatasaray" },
            { nom: "Matías Vecino", poste: "Milieu", club: "Lazio" },
            { nom: "Luis Suárez", poste: "Attaquant", club: "Inter Miami" },
            { nom: "Edinson Cavani", poste: "Attaquant", club: "Valencia" },
            { nom: "Darwin Núñez", poste: "Attaquant", club: "Liverpool" },
            { nom: "Facundo Torres", poste: "Attaquant", club: "Orlando City" },
            { nom: "Maximiliano Araújo", poste: "Attaquant", club: "Sporting CP" }
        ]
    },
    "Uzbekistan": {
        entraineur: "Srecko Katanec",
        titres: [],
        participations: [
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Utkir Yusupov", poste: "Gardien", club: "Lokomotiv Toshkent" },
            { nom: "Eldor Shomurodov", poste: "Attaquant", club: "Roma" },
            { nom: "Jasur Yakhshiboev", poste: "Attaquant", club: "FK Bunyodkor" },
            { nom: "Otabek Shukurov", poste: "Défenseur", club: "Pakhtakor" },
            { nom: "Sanjar Tursunov", poste: "Défenseur", club: "FK Bunyodkor" },
            { nom: "Islom Tukhtakhujaev", poste: "Défenseur", club: "Pakhtakor" },
            { nom: "Sherzod Nasrullayev", poste: "Milieu", club: "Lokomotiv Toshkent" },
            { nom: "Jaloliddin Masharipov", poste: "Milieu", club: "FK Bunyodkor" },
            { nom: "Dostonbek Khamdamov", poste: "Milieu", club: "Pakhtakor" },
            { nom: "Odil Ahmedov", poste: "Milieu", club: "Al-Ain" },
            { nom: "Abbosbek Fayzullaev", poste: "Milieu", club: "Lokomotiv Toshkent" },
            { nom: "Nodir Tursunov", poste: "Attaquant", club: "Pakhtakor" }
        ]
    }
}
