const effectifs = {
    "France": {
        entraineur: "Didier Deschamps",
        titres: ["Champion du Monde 1998", "Champion du Monde 2018"],
        participations: [
            { annee: 1930, phase: "1er tour" },
            { annee: 1934, phase: "1er tour" },
            { annee: 1938, phase: "QF" },
            { annee: 1954, phase: "1er tour" },
            { annee: 1958, phase: "3e place" },
            { annee: 1966, phase: "1er tour" },
            { annee: 1978, phase: "1er tour" },
            { annee: 1982, phase: "4e place" },
            { annee: 1986, phase: "3e place" },
            { annee: 1998, phase: "Vainqueur" },
            { annee: 2002, phase: "1er tour" },
            { annee: 2006, phase: "Finaliste" },
            { annee: 2010, phase: "1er tour" },
            { annee: 2014, phase: "QF" },
            { annee: 2018, phase: "Vainqueur" },
            { annee: 2022, phase: "Finaliste" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Mike Maignan", poste: "Gardien", club: "AC Milan" },
            { nom: "Brice Samba", poste: "Gardien", club: "RC Lens" },
            { nom: "Alphonse Areola", poste: "Gardien", club: "West Ham" },
            { nom: "Jules Koundé", poste: "Défenseur", club: "FC Barcelone" },
            { nom: "Theo Hernandez", poste: "Défenseur", club: "AC Milan" },
            { nom: "William Saliba", poste: "Défenseur", club: "Arsenal" },
            { nom: "Dayot Upamecano", poste: "Défenseur", club: "Bayern Munich" },
            { nom: "Ibrahima Konaté", poste: "Défenseur", club: "Liverpool" },
            { nom: "Benjamin Pavard", poste: "Défenseur", club: "Inter Milan" },
            { nom: "N'Golo Kanté", poste: "Milieu", club: "Al-Ittihad" },
            { nom: "Aurélien Tchouaméni", poste: "Milieu", club: "Real Madrid" },
            { nom: "Adrien Rabiot", poste: "Milieu", club: "Marseille" },
            { nom: "Warren Zaïre-Emery", poste: "Milieu", club: "Paris SG" },
            { nom: "Eduardo Camavinga", poste: "Milieu", club: "Real Madrid" },
            { nom: "Matteo Guendouzi", poste: "Milieu", club: "Lazio Rome" },
            { nom: "Kylian Mbappé", poste: "Attaquant", club: "Real Madrid" },
            { nom: "Antoine Griezmann", poste: "Attaquant", club: "Atletico Madrid" },
            { nom: "Ousmane Dembélé", poste: "Attaquant", club: "Paris SG" },
            { nom: "Marcus Thuram", poste: "Attaquant", club: "Inter Milan" },
            { nom: "Randal Kolo Muani", poste: "Attaquant", club: "Juventus" },
            { nom: "Bradley Barcola", poste: "Attaquant", club: "Paris SG" },
            { nom: "Kingsley Coman", poste: "Attaquant", club: "Bayern Munich" },
            { nom: "Christopher Nkunku", poste: "Attaquant", club: "Chelsea" }
        ]
    },
    "Brazil": {
        entraineur: "Dorival Júnior",
        titres: ["Champion du Monde 1958", "Champion du Monde 1962", "Champion du Monde 1970", "Champion du Monde 1994", "Champion du Monde 2002"],
        participations: [
            { annee: 1930, phase: "SF" },
            { annee: 1934, phase: "1er tour" },
            { annee: 1938, phase: "3e place" },
            { annee: 1950, phase: "Finaliste" },
            { annee: 1954, phase: "QF" },
            { annee: 1958, phase: "Vainqueur" },
            { annee: 1962, phase: "Vainqueur" },
            { annee: 1966, phase: "1er tour" },
            { annee: 1970, phase: "Vainqueur" },
            { annee: 1974, phase: "4e place" },
            { annee: 1978, phase: "3e place" },
            { annee: 1982, phase: "2e tour" },
            { annee: 1986, phase: "QF" },
            { annee: 1990, phase: "R16" },
            { annee: 1994, phase: "Vainqueur" },
            { annee: 1998, phase: "Finaliste" },
            { annee: 2002, phase: "Vainqueur" },
            { annee: 2006, phase: "QF" },
            { annee: 2010, phase: "QF" },
            { annee: 2014, phase: "4e place" },
            { annee: 2018, phase: "QF" },
            { annee: 2022, phase: "QF" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Alisson Becker", poste: "Gardien", club: "Liverpool" },
            { nom: "Ederson", poste: "Gardien", club: "Manchester City" },
            { nom: "Weverton", poste: "Gardien", club: "Palmeiras" },
            { nom: "Danilo", poste: "Défenseur", club: "Juventus" },
            { nom: "Éder Militão", poste: "Défenseur", club: "Real Madrid" },
            { nom: "Marquinhos", poste: "Défenseur", club: "Paris SG" },
            { nom: "Gabriel Magalhães", poste: "Défenseur", club: "Arsenal" },
            { nom: "Guilherme Arana", poste: "Défenseur", club: "Atlético Mineiro" },
            { nom: "Casemiro", poste: "Milieu", club: "Manchester United" },
            { nom: "Bruno Guimarães", poste: "Milieu", club: "Newcastle" },
            { nom: "Lucas Paquetá", poste: "Milieu", club: "West Ham" },
            { nom: "Gerson", poste: "Milieu", club: "Flamengo" },
            { nom: "Vinícius Jr.", poste: "Attaquant", club: "Real Madrid" },
            { nom: "Rodrygo", poste: "Attaquant", club: "Real Madrid" },
            { nom: "Gabriel Martinelli", poste: "Attaquant", club: "Arsenal" },
            { nom: "Raphinha", poste: "Attaquant", club: "FC Barcelone" },
            { nom: "Endrick", poste: "Attaquant", club: "Real Madrid" },
            { nom: "Gabriel Barbosa", poste: "Attaquant", club: "Flamengo" }
        ]
    },
    "Argentina": {
        entraineur: "Lionel Scaloni",
        titres: ["Champion du Monde 1978", "Champion du Monde 1986", "Champion du Monde 2022"],
        participations: [
            { annee: 1930, phase: "Finaliste" },
            { annee: 1934, phase: "1er tour" },
            { annee: 1958, phase: "1er tour" },
            { annee: 1962, phase: "1er tour" },
            { annee: 1966, phase: "QF" },
            { annee: 1974, phase: "2e tour" },
            { annee: 1978, phase: "Vainqueur" },
            { annee: 1982, phase: "2e tour" },
            { annee: 1986, phase: "Vainqueur" },
            { annee: 1990, phase: "Finaliste" },
            { annee: 1994, phase: "R16" },
            { annee: 1998, phase: "QF" },
            { annee: 2002, phase: "1er tour" },
            { annee: 2006, phase: "QF" },
            { annee: 2010, phase: "QF" },
            { annee: 2014, phase: "Finaliste" },
            { annee: 2018, phase: "R16" },
            { annee: 2022, phase: "Vainqueur" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Emiliano Martínez", poste: "Gardien", club: "Aston Villa" },
            { nom: "Franco Armani", poste: "Gardien", club: "River Plate" },
            { nom: "Nahuel Molina", poste: "Défenseur", club: "Atletico Madrid" },
            { nom: "Gonzalo Montiel", poste: "Défenseur", club: "Nottingham Forest" },
            { nom: "Cristian Romero", poste: "Défenseur", club: "Tottenham" },
            { nom: "Lisandro Martínez", poste: "Défenseur", club: "Manchester United" },
            { nom: "Nicolás Otamendi", poste: "Défenseur", club: "Benfica" },
            { nom: "Nicolás Tagliafico", poste: "Défenseur", club: "Lyon" },
            { nom: "Rodrigo De Paul", poste: "Milieu", club: "Atletico Madrid" },
            { nom: "Enzo Fernández", poste: "Milieu", club: "Chelsea" },
            { nom: "Leandro Paredes", poste: "Milieu", club: "Roma" },
            { nom: "Alexis Mac Allister", poste: "Milieu", club: "Liverpool" },
            { nom: "Lionel Messi", poste: "Attaquant", club: "Inter Miami" },
            { nom: "Ángel Di María", poste: "Attaquant", club: "Benfica" },
            { nom: "Lautaro Martínez", poste: "Attaquant", club: "Inter Milan" },
            { nom: "Julián Álvarez", poste: "Attaquant", club: "Atletico Madrid" },
            { nom: "Paulo Dybala", poste: "Attaquant", club: "Roma" }
        ]
    },
    "Germany": {
        entraineur: "Julian Nagelsmann",
        titres: ["Champion du Monde 1954", "Champion du Monde 1974", "Champion du Monde 1990", "Champion du Monde 2014"],
        participations: [
            { annee: 1934, phase: "3e place" },
            { annee: 1938, phase: "1er tour" },
            { annee: 1954, phase: "Vainqueur" },
            { annee: 1958, phase: "4e place" },
            { annee: 1962, phase: "QF" },
            { annee: 1966, phase: "Finaliste" },
            { annee: 1970, phase: "3e place" },
            { annee: 1974, phase: "Vainqueur" },
            { annee: 1978, phase: "2e tour" },
            { annee: 1982, phase: "Finaliste" },
            { annee: 1986, phase: "Finaliste" },
            { annee: 1990, phase: "Vainqueur" },
            { annee: 1994, phase: "QF" },
            { annee: 1998, phase: "QF" },
            { annee: 2002, phase: "Finaliste" },
            { annee: 2006, phase: "3e place" },
            { annee: 2010, phase: "3e place" },
            { annee: 2014, phase: "Vainqueur" },
            { annee: 2018, phase: "1er tour" },
            { annee: 2022, phase: "1er tour" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Manuel Neuer", poste: "Gardien", club: "Bayern Munich" },
            { nom: "Marc-André ter Stegen", poste: "Gardien", club: "FC Barcelone" },
            { nom: "Alexander Nübel", poste: "Gardien", club: "Stuttgart" },
            { nom: "Toni Rüdiger", poste: "Défenseur", club: "Real Madrid" },
            { nom: "Joshua Kimmich", poste: "Défenseur", club: "Bayern Munich" },
            { nom: "Nico Schlotterbeck", poste: "Défenseur", club: "Borussia Dortmund" },
            { nom: "Jonathan Tah", poste: "Défenseur", club: "Bayer Leverkusen" },
            { nom: "Maximilian Mittelstädt", poste: "Défenseur", club: "Stuttgart" },
            { nom: "Florian Wirtz", poste: "Milieu", club: "Bayer Leverkusen" },
            { nom: "Jamal Musiala", poste: "Milieu", club: "Bayern Munich" },
            { nom: "Leon Goretzka", poste: "Milieu", club: "Bayern Munich" },
            { nom: "Robert Andrich", poste: "Milieu", club: "Bayer Leverkusen" },
            { nom: "Pascal Groß", poste: "Milieu", club: "Borussia Dortmund" },
            { nom: "Thomas Müller", poste: "Attaquant", club: "Bayern Munich" },
            { nom: "Kai Havertz", poste: "Attaquant", club: "Arsenal" },
            { nom: "Leroy Sané", poste: "Attaquant", club: "Bayern Munich" },
            { nom: "Niclas Füllkrug", poste: "Attaquant", club: "West Ham" },
            { nom: "Chris Führich", poste: "Attaquant", club: "Stuttgart" }
        ]
    },
    "Spain": {
        entraineur: "Luis de la Fuente",
        titres: ["Champion du Monde 2010"],
        participations: [
            { annee: 1934, phase: "QF" },
            { annee: 1950, phase: "4e place" },
            { annee: 1962, phase: "1er tour" },
            { annee: 1966, phase: "1er tour" },
            { annee: 1978, phase: "1er tour" },
            { annee: 1982, phase: "2e tour" },
            { annee: 1986, phase: "QF" },
            { annee: 1990, phase: "R16" },
            { annee: 1994, phase: "QF" },
            { annee: 1998, phase: "R16" },
            { annee: 2002, phase: "QF" },
            { annee: 2006, phase: "R16" },
            { annee: 2010, phase: "Vainqueur" },
            { annee: 2014, phase: "1er tour" },
            { annee: 2018, phase: "R16" },
            { annee: 2022, phase: "QF" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "David Raya", poste: "Gardien", club: "Arsenal" },
            { nom: "Unai Simón", poste: "Gardien", club: "Athletic Club" },
            { nom: "Dani Vivian", poste: "Défenseur", club: "Athletic Club" },
            { nom: "Daniel Carvajal", poste: "Défenseur", club: "Real Madrid" },
            { nom: "Aymeric Laporte", poste: "Défenseur", club: "Al-Nassr" },
            { nom: "Pau Cubarsí", poste: "Défenseur", club: "FC Barcelone" },
            { nom: "Alejandro Grimaldo", poste: "Défenseur", club: "Bayer Leverkusen" },
            { nom: "Marc Cucurella", poste: "Défenseur", club: "Chelsea" },
            { nom: "Rodri", poste: "Milieu", club: "Manchester City" },
            { nom: "Pedri", poste: "Milieu", club: "FC Barcelone" },
            { nom: "Fabian Ruiz", poste: "Milieu", club: "Paris SG" },
            { nom: "Martin Zubimendi", poste: "Milieu", club: "Arsenal" },
            { nom: "Dani Olmo", poste: "Milieu", club: "FC Barcelone" },
            { nom: "Fermín López", poste: "Milieu", club: "FC Barcelone" },
            { nom: "Álvaro Morata", poste: "Attaquant", club: "AC Milan" },
            { nom: "Mikel Oyarzabal", poste: "Attaquant", club: "Real Sociedad" },
            { nom: "Nico Williams", poste: "Attaquant", club: "Athletic Club" },
            { nom: "Lamine Yamal", poste: "Attaquant", club: "FC Barcelone" },
            { nom: "Ayoze Pérez", poste: "Attaquant", club: "Villarreal" }
        ]
    },
    "England": {
        entraineur: "Lee Carsley",
        titres: ["Champion du Monde 1966"],
        participations: [
            { annee: 1950, phase: "1er tour" },
            { annee: 1954, phase: "QF" },
            { annee: 1958, phase: "1er tour" },
            { annee: 1962, phase: "QF" },
            { annee: 1966, phase: "Vainqueur" },
            { annee: 1970, phase: "QF" },
            { annee: 1982, phase: "2e tour" },
            { annee: 1986, phase: "QF" },
            { annee: 1990, phase: "4e place" },
            { annee: 1998, phase: "R16" },
            { annee: 2002, phase: "QF" },
            { annee: 2006, phase: "QF" },
            { annee: 2010, phase: "R16" },
            { annee: 2014, phase: "1er tour" },
            { annee: 2018, phase: "4e place" },
            { annee: 2022, phase: "QF" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Jordan Pickford", poste: "Gardien", club: "Everton" },
            { nom: "Aaron Ramsdale", poste: "Gardien", club: "Southampton" },
            { nom: "Dean Henderson", poste: "Gardien", club: "Crystal Palace" },
            { nom: "Kyle Walker", poste: "Défenseur", club: "Manchester City" },
            { nom: "Reece James", poste: "Défenseur", club: "Chelsea" },
            { nom: "Harry Maguire", poste: "Défenseur", club: "Manchester United" },
            { nom: "John Stones", poste: "Défenseur", club: "Manchester City" },
            { nom: "Marc Guehi", poste: "Défenseur", club: "Crystal Palace" },
            { nom: "Luke Shaw", poste: "Défenseur", club: "Manchester United" },
            { nom: "Kieran Trippier", poste: "Défenseur", club: "Newcastle" },
            { nom: "Declan Rice", poste: "Milieu", club: "Arsenal" },
            { nom: "Jude Bellingham", poste: "Milieu", club: "Real Madrid" },
            { nom: "Kobbie Mainoo", poste: "Milieu", club: "Manchester United" },
            { nom: "Conor Gallagher", poste: "Milieu", club: "Atletico Madrid" },
            { nom: "Phil Foden", poste: "Milieu", club: "Manchester City" },
            { nom: "Harry Kane", poste: "Attaquant", club: "Bayern Munich" },
            { nom: "Marcus Rashford", poste: "Attaquant", club: "Aston Villa" },
            { nom: "Bukayo Saka", poste: "Attaquant", club: "Arsenal" },
            { nom: "Ollie Watkins", poste: "Attaquant", club: "Aston Villa" },
            { nom: "Cole Palmer", poste: "Attaquant", club: "Chelsea" },
            { nom: "Anthony Gordon", poste: "Attaquant", club: "Newcastle" }
        ]
    },
    "Portugal": {
        entraineur: "Roberto Martínez",
        titres: [],
        participations: [
            { annee: 1966, phase: "3e place" },
            { annee: 1986, phase: "1er tour" },
            { annee: 2002, phase: "1er tour" },
            { annee: 2006, phase: "4e place" },
            { annee: 2010, phase: "R16" },
            { annee: 2014, phase: "1er tour" },
            { annee: 2018, phase: "R16" },
            { annee: 2022, phase: "QF" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Diogo Costa", poste: "Gardien", club: "FC Porto" },
            { nom: "Rui Patrício", poste: "Gardien", club: "Roma" },
            { nom: "Diogo Dalot", poste: "Défenseur", club: "Manchester United" },
            { nom: "Rúben Dias", poste: "Défenseur", club: "Manchester City" },
            { nom: "Pepe", poste: "Défenseur", club: "FC Porto" },
            { nom: "Nuno Mendes", poste: "Défenseur", club: "Paris SG" },
            { nom: "João Cancelo", poste: "Défenseur", club: "FC Barcelone" },
            { nom: "Rúben Neves", poste: "Milieu", club: "Al-Hilal" },
            { nom: "Vitinha", poste: "Milieu", club: "Paris SG" },
            { nom: "João Palhinha", poste: "Milieu", club: "Bayern Munich" },
            { nom: "Bruno Fernandes", poste: "Milieu", club: "Manchester United" },
            { nom: "Bernardo Silva", poste: "Milieu", club: "Manchester City" },
            { nom: "Cristiano Ronaldo", poste: "Attaquant", club: "Al-Nassr" },
            { nom: "Rafael Leão", poste: "Attaquant", club: "AC Milan" },
            { nom: "Gonçalo Ramos", poste: "Attaquant", club: "Paris SG" },
            { nom: "Pedro Neto", poste: "Attaquant", club: "Chelsea" },
            { nom: "João Félix", poste: "Attaquant", club: "FC Barcelone" }
        ]
    },
    "Netherlands": {
        entraineur: "Ronald Koeman",
        titres: [],
        participations: [
            { annee: 1934, phase: "1er tour" },
            { annee: 1938, phase: "1er tour" },
            { annee: 1974, phase: "Finaliste" },
            { annee: 1978, phase: "Finaliste" },
            { annee: 1990, phase: "R16" },
            { annee: 1994, phase: "QF" },
            { annee: 1998, phase: "4e place" },
            { annee: 2006, phase: "R16" },
            { annee: 2010, phase: "Finaliste" },
            { annee: 2014, phase: "3e place" },
            { annee: 2022, phase: "QF" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Bart Verbruggen", poste: "Gardien", club: "Brighton" },
            { nom: "Mark Flekken", poste: "Gardien", club: "Brentford" },
            { nom: "Denzel Dumfries", poste: "Défenseur", club: "Inter Milan" },
            { nom: "Virgil van Dijk", poste: "Défenseur", club: "Liverpool" },
            { nom: "Stefan de Vrij", poste: "Défenseur", club: "Inter Milan" },
            { nom: "Nathan Aké", poste: "Défenseur", club: "Manchester City" },
            { nom: "Daley Blind", poste: "Défenseur", club: "Girona" },
            { nom: "Frenkie de Jong", poste: "Milieu", club: "FC Barcelone" },
            { nom: "Tijjani Reijnders", poste: "Milieu", club: "AC Milan" },
            { nom: "Teun Koopmeiners", poste: "Milieu", club: "Juventus" },
            { nom: "Jerdy Schouten", poste: "Milieu", club: "Bologna" },
            { nom: "Cody Gakpo", poste: "Attaquant", club: "Liverpool" },
            { nom: "Donyell Malen", poste: "Attaquant", club: "Aston Villa" },
            { nom: "Steven Bergwijn", poste: "Attaquant", club: "Ajax" },
            { nom: "Memphis Depay", poste: "Attaquant", club: "Atlético Madrid" },
            { nom: "Wout Weghorst", poste: "Attaquant", club: "Hoffenheim" }
        ]
    },
    "Morocco": {
        entraineur: "Walid Regragui",
        titres: [],
        participations: [
            { annee: 1970, phase: "1er tour" },
            { annee: 1986, phase: "R16" },
            { annee: 1994, phase: "1er tour" },
            { annee: 1998, phase: "1er tour" },
            { annee: 2018, phase: "1er tour" },
            { annee: 2022, phase: "4e place" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Yassine Bounou", poste: "Gardien", club: "Al-Hilal" },
            { nom: "Munir Mohamedi", poste: "Gardien", club: "RC Lens" },
            { nom: "Achraf Hakimi", poste: "Défenseur", club: "Paris SG" },
            { nom: "Noussair Mazraoui", poste: "Défenseur", club: "Manchester United" },
            { nom: "Romain Saïss", poste: "Défenseur", club: "Beşiktaş" },
            { nom: "Nayef Aguerd", poste: "Défenseur", club: "West Ham" },
            { nom: "Yahia Attiyat Allah", poste: "Défenseur", club: "Wydad AC" },
            { nom: "Azzedine Ounahi", poste: "Milieu", club: "OM" },
            { nom: "Selim Amallah", poste: "Milieu", club: "Standard Liège" },
            { nom: "Sofyan Amrabat", poste: "Milieu", club: "Fiorentina" },
            { nom: "Bilal El Khannous", poste: "Milieu", club: "Genk" },
            { nom: "Hakim Ziyech", poste: "Attaquant", club: "Galatasaray" },
            { nom: "Youssef En-Nesyri", poste: "Attaquant", club: "Fenerbahçe" },
            { nom: "Sofiane Boufal", poste: "Attaquant", club: "Al-Qadsiah" },
            { nom: "Abde Ezzalzouli", poste: "Attaquant", club: "Betis" },
            { nom: "Zakaria Aboukhlal", poste: "Attaquant", club: "Toulouse" }
        ]
    },
    "United States": {
        entraineur: "Mauricio Pochettino",
        titres: [],
        participations: [
            { annee: 1930, phase: "3e place" },
            { annee: 1934, phase: "1er tour" },
            { annee: 1950, phase: "1er tour" },
            { annee: 1990, phase: "1er tour" },
            { annee: 1994, phase: "R16" },
            { annee: 1998, phase: "1er tour" },
            { annee: 2002, phase: "QF" },
            { annee: 2006, phase: "1er tour" },
            { annee: 2010, phase: "R16" },
            { annee: 2014, phase: "R16" },
            { annee: 2022, phase: "R16" },
            { annee: 2026, phase: "—" }
        ],
        joueurs: [
            { nom: "Matt Turner", poste: "Gardien", club: "Crystal Palace" },
            { nom: "Patrick Schulte", poste: "Gardien", club: "Columbus Crew" },
            { nom: "Sergino Dest", poste: "Défenseur", club: "PSV Eindhoven" },
            { nom: "Joe Scally", poste: "Défenseur", club: "Borussia Mönchengladbach" },
            { nom: "Tim Ream", poste: "Défenseur", club: "Charlotte FC" },
            { nom: "Chris Richards", poste: "Défenseur", club: "Crystal Palace" },
            { nom: "Antonee Robinson", poste: "Défenseur", club: "Fulham" },
            { nom: "Yunus Musah", poste: "Milieu", club: "AC Milan" },
            { nom: "Tyler Adams", poste: "Milieu", club: "Bournemouth" },
            { nom: "Weston McKennie", poste: "Milieu", club: "Juventus" },
            { nom: "Gio Reyna", poste: "Milieu", club: "Borussia Dortmund" },
            { nom: "Christian Pulisic", poste: "Attaquant", club: "AC Milan" },
            { nom: "Josh Sargent", poste: "Attaquant", club: "Norwich City" },
            { nom: "Ricardo Pepi", poste: "Attaquant", club: "PSV Eindhoven" },
            { nom: "Tim Weah", poste: "Attaquant", club: "Juventus" },
            { nom: "Folarin Balogun", poste: "Attaquant", club: "Monaco" }
        ]
    }
}
