const traductions = {
    "Mexico": "Mexique",
    "South Africa": "Afrique du Sud",
    "South Korea": "Corée du Sud",
    "Czech Republic": "République Tchèque",
    "Canada": "Canada",
    "Switzerland": "Suisse",
    "Qatar": "Qatar",
    "Bosnia and Herzegovina": "Bosnie-Herzégovine",
    "Brazil": "Brésil",
    "Morocco": "Maroc",
    "Haiti": "Haïti",
    "Scotland": "Écosse",
    "USA": "États-Unis",
    "Paraguay": "Paraguay",
    "Australia": "Australie",
    "Turkiye": "Turquie",
    "Germany": "Allemagne",
    "Curaçao": "Curaçao",
    "Ivory Coast": "Côte d'Ivoire",
    "Ecuador": "Équateur",
    "Netherlands": "Pays-Bas",
    "Japan": "Japon",
    "Tunisia": "Tunisie",
    "Sweden": "Suède",
    "Belgium": "Belgique",
    "Egypt": "Égypte",
    "Iran": "Iran",
    "New Zealand": "Nouvelle-Zélande",
    "Spain": "Espagne",
    "Cape Verde": "Cap-Vert",
    "Saudi Arabia": "Arabie Saoudite",
    "Uruguay": "Uruguay",
    "France": "France",
    "Senegal": "Sénégal",
    "Norway": "Norvège",
    "Iraq": "Irak",
    "Argentina": "Argentine",
    "Algeria": "Algérie",
    "Austria": "Autriche",
    "Jordan": "Jordanie",
    "Portugal": "Portugal",
    "Colombia": "Colombie",
    "Uzbekistan": "Ouzbékistan",
    "Congo DR": "Congo RD",
    "England": "Angleterre",
    "Croatia": "Croatie",
    "Ghana": "Ghana",
    "Panama": "Panama"
}